### ISSUE TITLE
Intl.DateTimeFormat not polyfilled correctly and always flag crashes Firefox

### ISSUE THREAD

**Issue by nickrttn** [Financial-Times/polyfill-library#1012]
# Bug report

The `Intl.DateTimeFormat` polyfill doesn't correctly detect support for `formatRange` in Firefox (86). That browser doesn't support `formatRange` and `formatRangeToParts` but also doesn't receive the polyfill by default.

If the `always` flag is passed to force the polyfill Firefox will report an error `Uncaught TypeError: Setter must be a function` coming from the polyfill script.

## Expected behaviour

- `formatRange` and `formatRangeToParts` to be polyfilled when requesting the polyfill for a browser that has parts of `Intl.DateTimeFormat`.
- `always` flag not to cause an error

## Steps to reproduce

- Request the Intl.DateTimeFormat polyfill and the `en` locale (with/without `|always`) in Firefox

## Environment

- Firefox 86
- MBP, macOS Big Sur

![Screenshot 2021-03-10 at 11 17 54](https://user-images.githubusercontent.com/2504906/110614111-e789c300-8189-11eb-88ad-9130d4c75820.png)

**Comment by romainmenke** [comment]
@JakeChampion MDN is correct. Firefox doesn't have support for `formatRange`

```js
var date1 = new Date(Date.UTC(2007, 0, 10, 10, 0, 0));
var date2 = new Date(Date.UTC(2007, 0, 10, 11, 0, 0));

var fmt1 = new Intl.DateTimeFormat("en", {
		year: '2-digit',
		month: 'numeric',
		day: 'numeric',
		hour: 'numeric',
		minute: 'numeric'
});

console.log(!!fmt1.formatRange(date1, date2)) // Uncaught TypeError: fmt1.formatRange is not a function
```

**Comment by JakeChampion** [comment]
Thank you for confirming @romainmenke 🙌 

I've raised a pull-request to serve this polyfill to all Firefox versions -- https://github.com/Financial-Times/polyfill-library/pull/1013

**Comment by romainmenke** [comment]
I think the same issue also exists for other browsers.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange#browser_compatibility

ran some tests and seeing the same results for Blink,Webkit,Gecko as stated by MDN

**Comment by romainmenke** [comment]
They support it, but from `76`
So this should work : https://github.com/Financial-Times/polyfill-library/pull/1013/commits/4ca7ff2a1474daea8bbf59c0f0d40a6c37fafdf4#diff-77edc5e4fe23dd90eb39468935b117d0add719ecfc03b83473a1980568198b9eR39

**Comment by longlho** [comment]
@JakeChampion do you still need me to look at anything?

**Comment by JakeChampion** [comment]
> @JakeChampion do you still need me to look at anything?

I don't think so, @romainmenke helped solve this 😄

**Comment by nickrttn** [comment]
Thanks for the quick action on this issue folks!

The polyfill is now correctly being served. The `Intl.DateTimeFormat` polyfill does still break with the `|always` flag. It also happens in Chrome and likely other browsers as well. Should I create a new issue for that?

**Comment by JakeChampion** [comment]
> Thanks for the quick action on this issue folks!
> 
> The polyfill is now correctly being served. The `Intl.DateTimeFormat` polyfill does still break with the `|always` flag. It also happens in Chrome and likely other browsers as well. Should I create a new issue for that?

We haven't released this change onto npm or onto polyfill.io yet

**Comment by nickrttn** [comment]
🤦 my bad :) I'll keep an eye on your releases
