### ISSUE TITLE
Question:  Should we polyfill the "Additional Built-in Properties"

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/polyfill-library#104]
https://tc39.github.io/ecma262/#sec-additional-built-in-properties

- escape
- unescape
- String.prototype.substr
- String.prototype.anchor
- String.prototype.big
- String.prototype.blink
- String.prototype.bold
- String.prototype.fixed
- String.prototype.fontcolor
- String.prototype.fontsize
- String.prototype.italics
- String.prototype.link
- String.prototype.small
- String.prototype.strike
- String.prototype.sub
- String.prototype.sup
- Date.prototype.getYear 
- Date.prototype.setYear 
- Date.prototype.toGMTString
- RegExp.prototype.compile

**Comment by chee** [comment]
yes, i think so.

> When the ECMAScript host is a web browser the following additional properties of the standard built-in objects are defined.

polyfill-library is for web browser, ipsy foxy polyfill

**Comment by JakeChampion** [comment]
These are all implemented in the browsers we support already, there is no need to polyfill them.
