### ISSUE TITLE
Intl.DateTimeFormat is missing timezone data

### ISSUE THREAD

**Issue by eltonio450** [Financial-Times/polyfill-library#1042]
Hello everyone,

### Bug/feature

I am not sure if it's a bug or an intended behavior

## What

Intl polyfill is missing timezone data. 

The full polyfill could include timezone data or there could be an extra polyfill to add this data

## Details

The polyfill in question is here : 
https://formatjs.io/docs/polyfills/intl-datetimeformat/

for the moment, if we want to have timezone support, for example for Safari, we have to add

`import "@formatjs/intl-datetimeformat/add-all-tz"` to our code

Example :
User Agent : Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1
Polyfill: https://polyfill.io/v3/polyfill.js?features=Intl

Results :

``` 
* Features requested: Intl
 * 
 * - Intl.Locale, License: MIT (required by "Intl.PluralRules.~locale.en", "Intl.PluralRules", "Intl")
 * - Intl.PluralRules, License: MIT (required by "Intl.PluralRules.~locale.en", "Intl")
 * - Intl.NumberFormat, License: MIT (required by "Intl.NumberFormat.~locale.en", "Intl")
 * - Intl.DateTimeFormat, License: MIT (required by "Intl.DateTimeFormat.~locale.en", "Intl")
 * - Intl.DateTimeFormat.~locale.en, License: MIT (required by "Intl")
 * - Intl.NumberFormat.~locale.en, License: MIT (required by "Intl")
 * - Intl.PluralRules.~locale.en, License: MIT (required by "Intl") */
```

But InitializeDateTimeFormat fails if used with a timezone (any timezone)

I digged a bit in the repo but did not find anything related to this

Not sure how to contribute, but if needed, I'd be glad to help :)

**Comment by JakeChampion** [comment]
@longlho, it sounds like the datetimeformat polyfills might be missing the timezone data, is there a way to add the data for individual timezones like we do for locales?

**Comment by longlho** [comment]
Technically yes but tz data have strong linking relationship and aliases so it's pretty messy. We distributed 2 tz bundles: everything & golden. Golden is basically the most popular timezones. I think maybe we can surface that as a separate feature? For reference IE11 has DateTimeFormat but no timezone.

**Comment by JakeChampion** [comment]
> Technically yes but tz data have strong linking relationship and aliases so it's pretty messy. We distributed 2 tz bundles: everything & golden. Golden is basically the most popular timezones. I think maybe we can surface that as a separate feature? For reference IE11 has DateTimeFormat but no timezone.

A separate feature makes sense :+1:

**Comment by longlho** [comment]
I unfortunately won't have time in the few weeks so if anyone wants to tackle it that'd be great.

**Comment by tgandee79** [comment]
I'll see if I can tackle it.  

Separate featuring meaning a new addition to the Polyfill for consumption:  
```
https://polyfill.com/v3/polyfill.min.js?features=Intl.DateTimeFormat,Intl.DateTimeFormat.prototype.formatToParts,Intl.DateTimeFormat.~locale.en-GB,Intl.DateTimeFormat.timeZone
```

??
