### ISSUE TITLE
tabs in source files for a11y and consistency?

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1060]
reading on a11y in source code : https://dev.to/alexandersandberg/why-we-should-default-to-tabs-instead-of-spaces-for-an-accessible-first-environment-101f

At this point the code base is fairly inconsistent and imho it would benefit from a single convention for whitespace.
When making changes I try to work per file and use tabs or spaces depending on the surrounding code.
But it is a bit distracting and often I have to add extra commits with fixes after copy/paste from another file with a different format.

I don't mind doing the needed updates and I also don't mind not doing anything at all :)

**Comment by JakeChampion** [comment]
Thanks for this issue @romainmenke, I've opened a pull-request to resolve this -- https://github.com/Financial-Times/polyfill-library/pull/1063

**Comment by romainmenke** [comment]
Awesome! Thank you @JakeChampion 🎉
