### ISSUE TITLE
publishing releases fails

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1073]
https://github.com/Financial-Times/polyfill-library/runs/3114628872

_maybe you are aware and had been planning to release this manually later_

**Comment by JakeChampion** [comment]
Hi @romainmenke, yes I've been trying to release manually but came across an issue with `npm run build` not finding the correct localisation dependency for the Intl.PluralRules polyfills

I've opened a ticket on the upstream project, hopefully it can be resolved and we can release a new version of polyfill-library -- https://github.com/formatjs/formatjs/issues/3058

**Comment by romainmenke** [comment]
Is it possible you were using node 15 or 16?
When I forget to switch to node ±12 I also see errors.

**Comment by JakeChampion** [comment]
I'll try node 12 👍

**Comment by JakeChampion** [comment]
@romainmenke That was the issue 🤦 I'll pin the node version using volta in this project to avoid this in the future

**Comment by JakeChampion** [comment]
version 3.106.0 and 3.107.0 are now published 🎉

**Comment by romainmenke** [comment]
Oh Volta looks cool! We have been using nvm but it's slow :)

**Comment by JakeChampion** [comment]
> Oh Volta looks cool! We have been using nvm but it's slow :)

Volta is so fast that the only time I notice it switching is when it needs to download a different node version from the internet - I highly recommend volta 👍
