### ISSUE TITLE
timeZone data appears to be needed any time the Intl.DateTimeFormat polyfill is loaded

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1075]
https://github.com/Financial-Times/polyfill-library/blob/7ba1ec95e4f3037165237d88ae1ae02f7df4d88b/polyfills/Intl/DateTimeFormat/%7EtimeZone/golden/config.toml#L21-L31

As discussed and tested [here](https://github.com/Financial-Times/polyfill-library/pull/1061#issuecomment-857835247) I assumed that the timeZone data would not need to be loaded everywhere and the `Intl.DateTimeFormat` polyfill could utilise native support.

When testing this that appears to be not true :/

Example in Chrome 64 :

```
	new Intl.DateTimeFormat('en', {
		timeZone: 'Europe/Brussels',
		timeZoneName: 'long'
	}).format(new Date(Date.UTC(2012, 11, 20, 3, 0, 0, 200)))
```

This works without any polyfills but fails when `Intl.DateTimeFormat` is included.

@longlho Is it true that we need to load the timeZone data in all browsers that need `Intl.DateTimeFormat`?
Or is there something I might be missing?

**Comment by longlho** [comment]
Yes browsers don't expose raw iana tz data.

**Comment by romainmenke** [comment]
Thank you for the quick reply :)
