### ISSUE TITLE
weekly checkup with polyfill combinations fails on iOS

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1079]
see : https://github.com/Financial-Times/polyfill-library/actions/workflows/test-polyfills-weekly.yml

traced this to an exception in `polyfills/Symbol/asyncIterator/polyfill.js` on iOS 11.1 and up.
The polyfill isn't needed there but loaded anyway. The exception causes test failures as the polyfills aren't fully applied.

Should be resolved by updating the needed dependencies to get this change here : https://github.com/Financial-Times/useragent_parser/pull/101

also see : https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/package.json#L22

**Comment by JakeChampion** [comment]
Thanks for the issue @romainmenke - I've opened a pull-request to update the version of polyfill-useragent-normaliser being used -- https://github.com/Financial-Times/polyfill-library/pull/1080

**Comment by romainmenke** [comment]
Thank you @JakeChampion

weekly tests now pass on iOS and we see the expected drop off in number of tests. 🎉 

```
 • Browser: ios/10 Test config: targeted /          ✓ 482 tests  23 seconds to complete
 • Browser: ios/10 Test config: targeted / combined ✓ 483 tests  34 seconds to complete
 • Browser: ios/11 Test config: targeted /          ✓ 416 tests  18 seconds to complete
 • Browser: ios/11 Test config: targeted / combined ✓ 417 tests  28 seconds to complete
 • Browser: ios/12 Test config: targeted /          ✓ 211 tests  9 seconds to complete
 • Browser: ios/12 Test config: targeted / combined ✓ 211 tests  9 seconds to complete
 • Browser: ios/13 Test config: targeted /          ✓ 177 tests  8 seconds to complete
 • Browser: ios/13 Test config: targeted / combined ✓ 177 tests  9 seconds to complete
 • Browser: ios/14 Test config: targeted /          ✓ 150 tests  7 seconds to complete
 • Browser: ios/14 Test config: targeted / combined ✓ 150 tests  8 seconds to complete
```
