### ISSUE TITLE
WebAnimations is incorrectly polyfilled on Safari

### ISSUE THREAD

**Issue by bakura10** [Financial-Times/polyfill-library#1085]
Hi,

WebAnimations is natively available from Safari 13.1 on both Safari mobile and desktop. However it currently still serves a polyfill even on new iOS 15. As far as I know the Safari 13.1 implementation is on par with Chrome one.

**Comment by romainmenke** [comment]
@JakeChampion Do you have the time this week to roll out a release here and for the `polyfill-service`?
Totally fine if you don't :)

**Comment by JakeChampion** [comment]
V3.108 is now out :-)
https://github.com/Financial-Times/polyfill-library/releases/tag/v3.108.0

**Comment by romainmenke** [comment]
Thank you!

**Comment by bakura10** [comment]
Thanks @JakeChampion . It seems the last version is still 3.105: https://polyfill.io/v3/polyfill.min.js?features=WebAnimations

Does the deployment to production happens later? :)

**Comment by JakeChampion** [comment]
> Thanks @JakeChampion . It seems the last version is still 3.105: [polyfill.io/v3/polyfill.min.js?features=WebAnimations](https://polyfill.io/v3/polyfill.min.js?features=WebAnimations)
> 
> Does the deployment to production happens later? :)

I'm going to deploy to polyfill.io today 👍

**Comment by JakeChampion** [comment]
@bakura10 and @romainmenke here is the pull-request for the update -- https://github.com/Financial-Times/polyfill-service/pull/2641

**Comment by romainmenke** [comment]
Thank you @JakeChampion!

https://polyfill.io/v3/polyfill.js?features=WebAnimations

```
/* Polyfill service v3.108.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: WebAnimations
 *  */


/* No polyfills needed for current settings and browser */
```
