### ISSUE TITLE
window.crypto.randomUUID()

### ISSUE THREAD

**Issue by elf-pavlik** [Financial-Times/polyfill-library#1089]
Feature request

## What

polyfill.io doesn't provide polyfill for `window.crypto.randomUUID()`

## Details

Spec: https://github.com/WICG/uuid

>## Implementation status
> * [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1197594) - Shipping 92.
> * [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1723674) - Work in progress.
> * [WebKit](https://bugs.webkit.org/show_bug.cgi?id=229240) - Implemented, not shipped yet.

Polyfill: https://github.com/uuidjs/randomUUID

**Comment by romainmenke** [comment]
Have been working on this : https://github.com/romainmenke/polyfill-library/blob/crypto.randomUUID--sincere-snapping-turtle-cbbcdffcf3/polyfills/crypto/randomUUID/polyfill.js

It currently only lacks a good `randomUUID` implementation for IE 8-9 and other browsers lacking `Blob` support.
Haven't had the time yet to compare different approaches.

**Comment by JakeChampion** [comment]
We won't be implementing a polyfill for this, chee has explained the reasoning in a [comment on the draft PR](https://github.com/Financial-Times/polyfill-library/pull/1090#issuecomment-903159185), I have copied it below:

>this seems, to me, like a case where it would be better to fail than to provide a weak implementation. the draft says "Overwrite all elements of array with cryptographically secure random values" which is just not something we can polyfill.
