### ISSUE TITLE
Intl.Listformat not being loaded for macOS Catalina Safari v14.1 and higher

### ISSUE THREAD

**Issue by srikarsam** [Financial-Times/polyfill-library#1103]
Type: BUG

## What

`Intl.ListFormat` polyfill is not being loaded for Safari versions >= 14.1. I've observed that this feature is not available on macOS Catalina Safari V14.1 whereas it is available on macOS BigSur Safari V14.1

https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Intl/ListFormat/config.toml#L35

## Details

- `Intl.ListFormat` polyfill should be loaded for MacOS Catalina Safari v14.1 and higher
- Try loading this polyfill.io [link](https://polyfill.io/v3/polyfill.js?features=Intl.ListFormat) on macOS Catalina Safari v14.1 or higher. It says that polyfill is not needed for this browser whereas if we try to check the feature availability in the browser console, it's `undefined`.
- macOS version - 10.15.7
- Safari Version - 14.1.2 (15611.3.10.1.5, 15611)

<img src="https://user-images.githubusercontent.com/74644778/134852789-96c7d8ad-7868-409d-9d35-204144830028.png" width="50%" />

**Comment by romainmenke** [comment]
Is it possible to test if the feature exists in Safari 15 on Catalina?

Trying to judge the scope of this issue.
Very unfortunate that Safari can now have a different feature set for the same version.

**Comment by srikarsam** [comment]
Thanks for your reply @romainmenke !

I just upgraded safari to v15.0 Looks like it still don't have `Intl.ListFormat` support. Please find the screenshot below. Thank you!

![image](https://user-images.githubusercontent.com/74644778/134935491-bf856c0c-3c70-4a33-998d-416b7da89849.png)

**Comment by romainmenke** [comment]
Thank you for the extra info @srikarsam !
We'll have to think a bit about this as it seems that Safari versions in user agents are not a reliable way to detect `Intl` support.

I also wonder if there are other features missing in new Safari versions on Catalina :/

**Comment by romainmenke** [comment]
Follow up question, can you post your user agent string here?
I am wondering what info is in there.

**Comment by srikarsam** [comment]
@romainmenke Locale data is also missing. Please find the user agent below:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15`

**Comment by srikarsam** [comment]
Hey @romainmenke! Thanks for letting me know that this feature is OS dependant.

I ran the tests. Looks like `Intl.ListFormat` is the only one which is failing. Please find the screenshot below:

![image](https://user-images.githubusercontent.com/74644778/135030620-00830fef-d025-41f7-88eb-c43d023de5d0.png)

**Comment by longlho** [comment]
yeah ICU versions get updated on a separate cadence and we try to check for that in terms of capabilities & bugfixes
