### ISSUE TITLE
"ios_saf/11.0.0" es.symbol.description does not support

### ISSUE THREAD

**Issue by chenyulun** [Financial-Times/polyfill-library#1124]
# A bug report

## What

`Symbol('foo').description == 'foo'` in "ios_saf/11.0.0" return false

## Details

- Browser : Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
- Device IPhone 6 puls 11.4.1

![image](https://user-images.githubusercontent.com/15979948/141769173-279a849f-278a-440c-b830-7de345c2e234.png)

// node_modules/core-js-compat/data.json
```json
{
"es.symbol": {
    "android": "49",
    "chrome": "49",
    "deno": "1.0",
    "edge": "15",
    "electron": "0.37",
    "firefox": "51",
    "ios": "10.0",
    "node": "6.0",
    "opera": "36",
    "opera_mobile": "36",
    "safari": "10.0",
    "samsung": "5.0"
  },
  "es.symbol.description": {
    "android": "70",
    "chrome": "70",
    "deno": "1.0",
    "edge": "74",
    "electron": "5.0",
    "firefox": "63",
    "ios": "12.2",
    "node": "11.0",
    "opera": "57",
    "opera_mobile": "49",
    "safari": "12.1",
    "samsung": "10.0"
  }
}
```

**Comment by romainmenke** [comment]
Hi!

Can you share the polyfill.io url used?

**Comment by chenyulun** [comment]
`https://polyfill.io/v3/polyfill.min.js?features=default%2Ces2015%2Ces2016%2Ces2017%2Ces2018%2Ces2019`
I actually built the server myself, and I overwrote the value of 'default'
```js
const customAlias = new Map();
customAlias.set('default', [
  'default',
  'es2015',
  'es2016',
  'es2017',
  'es2018',
  'es2019',
  'es2020',
  'es2021',
  'globalThis',
  'queueMicrotask',
  // 'URL',
  'URL.prototype.toJSON',
  'URLSearchParams',
  // 'DOMTokenList',
  'DOMTokenList.prototype.@@iterator',
  'DOMTokenList.prototype.forEach',
  'DOMTokenList.prototype.replace',
  'NodeList.prototype.@@iterator',
  'NodeList.prototype.forEach',
  'URL.prototype.toJSON',
  'URLSearchParams',
  'Reflect',
  'Reflect.apply',
  'Reflect.construct',
  'Reflect.defineProperty',
  'Reflect.deleteProperty',
  'Reflect.get',
  'Reflect.getOwnPropertyDescriptor',
  'Reflect.getPrototypeOf',
  'Reflect.has',
  'Reflect.isExtensible',
  'Reflect.ownKeys',
  'Reflect.preventExtensions',
  'Reflect.set',
  'Reflect.setPrototypeOf',
  // 'setImmediate',
]);
```

**Comment by romainmenke** [comment]
Can you try adding `Symbol.prototype.description`?
It's a separate polyfill and isn't part of `default` or another alias.

**Comment by chenyulun** [comment]
I was wrong, I thought these attributes were added by default, so I added them again
```diff
// ....
'Reflect.preventExtensions',
  'Reflect.set',
  'Reflect.setPrototypeOf',
+ 'Symbol.prototype.description',
+ 'Symbol.for',
+ 'Symbol.isConcatSpreadable',
+ 'Symbol.keyFor',
  // 'setImmediate',
]);
```

**Comment by chenyulun** [comment]
The test results still fail
![image](https://user-images.githubusercontent.com/15979948/141779020-036b712b-d020-48dd-b70c-8f3fea97b818.png)

**Comment by romainmenke** [comment]
🤔 It should work : https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Symbol/prototype/description/tests.js#L19

Can you add the list of returned polyfills instead of the requested?

What is the type error in your logs?

**Comment by chenyulun** [comment]
`https://polyfill.io/v3/polyfill.min.js?features=default%2Ces2015%2Ces2016%2Ces2017%2Ces2018%2Ces2019%2CSymbol%2CSymbol.asyncIterator%2CSymbol.for%2CSymbol.hasInstance%2CSymbol.isConcatSpreadable%2CSymbol.iterator%2CSymbol.keyFor%2CSymbol.match%2CSymbol.prototype.description%2CSymbol.replace%2CSymbol.search%2CSymbol.species%2CSymbol.split%2CSymbol.toPrimitive%2CSymbol.unscopables%2CSymbol.toStringTag&flags=always`
add `flags=always`，
Add return all features can be verified
Is there something wrong with this document `polyfills/__dist/Symbol.prototype.description/meta.json`

```json
{
	"aliases": [],
	"dependencies": [
		"Symbol",
		"Object.defineProperty",
		"String.prototype.trim",
		"_ESAbstract.Type"
	],
	"license": "MIT",
	"spec": "https://tc39.github.io/proposal-Symbol-description/",
	"docs": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/description",
	"browsers": {
		"edge": "13 - 18",
		"edge_mob": ">= 13",
		"safari": "9 - 12.1",
		"chrome": "49 - 69",
		"firefox": "36 - 62",
		"firefox_mob": "36 - 62",
		"ios_saf": "9 - 12.1",
		"opera": "37 - 56",
		"samsung_mob": "5 - 10.1"
	},
	"detectSource": "\"description\"in self.Symbol.prototype\n",
	"baseDir": "Symbol/prototype/description",
	"hasTests": true,
	"isTestable": true,
	"isPublic": true,
	"size": 1012
}
```

**Comment by romainmenke** [comment]
I don't think that url is correct.
When using `always` you should also use `gated`.

I think the polyfill script is just throwing errors because of that and any polyfills after the error are not applied.

**Comment by JakeChampion** [comment]
I tested this on BrowserStack using an iPhone 6 and it looks to work correctly:
![image](https://user-images.githubusercontent.com/1569131/141783245-c59bce02-1151-4cae-9543-a07aecc0edfc.png)

The html I used was this:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <script>
    console.log(navigator.userAgent)
    console.log('loading https://polyfill.io/v3/polyfill.min.js?features=default,es2015,es2016,es2017,es2018,es2019,Symbol,Symbol.asyncIterator,Symbol.for,Symbol.hasInstance,Symbol.isConcatSpreadable,Symbol.iterator,Symbol.keyFor,Symbol.match,Symbol.prototype.description,Symbol.replace,Symbol.search,Symbol.species,Symbol.split,Symbol.toPrimitive,Symbol.unscopables,Symbol.toStringTag')
  </script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default,es2015,es2016,es2017,es2018,es2019,Symbol,Symbol.asyncIterator,Symbol.for,Symbol.hasInstance,Symbol.isConcatSpreadable,Symbol.iterator,Symbol.keyFor,Symbol.match,Symbol.prototype.description,Symbol.replace,Symbol.search,Symbol.species,Symbol.split,Symbol.toPrimitive,Symbol.unscopables,Symbol.toStringTag"></script>
  <script>
    console.log('loaded.');
    console.log("running Symbol('foo').description == 'foo'")
    console.log(Symbol('foo').description == 'foo')
  </script>
</head>
<body>

</body>
</html>
```

**Comment by chenyulun** [comment]
![image](https://user-images.githubusercontent.com/15979948/141783775-5d9a7401-de33-4a18-ae42-f61b155e224b.png)

**Comment by chenyulun** [comment]
![image](https://user-images.githubusercontent.com/15979948/141784814-e8944155-77ba-40b5-904d-692bd3ecccf5.png)

The flags in caniuse are not supported by iOS_SAF (iOS_SAF_11)

`core-js` shows that ios 12 supports this feature，
![image](https://user-images.githubusercontent.com/15979948/141785162-9cade50b-b89a-46ef-9ffe-7d743a41b1e6.png)

The reason why `polyfill.io` reported an error is that you did not make a judgment on whether to support it or not

**Comment by JakeChampion** [comment]
>  But the device I'm testing is iOS_SAf /11.0.0, which has`symbol.asynciterator `

> The reason why `polyfill.io` reported an error is that you did not make a judgment on whether to support it or not


We send the polyfill for Symbol.asyncIterator to iOS Safari versions below 11.1
https://github.com/Financial-Times/polyfill-library/blob/8b44935668e7b044e623aeade02bb38efb5ea91f/polyfills/Symbol/asyncIterator/config.toml#L15

This issue was opened for Symbol.prototype.description, could you please open another issue about Symbol.asyncIterator and we can close this issue if you think we've resolved the Symbol.prototype.description questions you raised

**Comment by chenyulun** [comment]
I began to doubt whether this solution was feasible. I packaged core-JS for various browsers directly, and determined that the UA returned the corresponding type of bundle (which could support Gzip and BR), instead of dynamically generating polyfill
