### ISSUE TITLE
Problems with Reflect.getPrototypeOf polyfill

### ISSUE THREAD

**Issue by TomazicM** [Financial-Times/polyfill-library#1132]
## What
I'm trying to use latest OpenLayers 6.9.0 in IE11 browser and have problems with the `Reflect.getPrototypeOf` polyfill.

## Details

This is the part of the OL helpers code that uses `Reflect.getPrototypeOf` method:
```
// Inspired by util.types implementation of Node.js
const TypedArrayPrototype = Reflect.getPrototypeOf(Uint8Array).prototype;
const getTypedArrayPrototypeSybolToStringTag = Reflect.getOwnPropertyDescriptor(TypedArrayPrototype, Symbol.toStringTag).get;
```
Problem is that polyfill returns `undefined` for `Reflect.getPrototypeOf(Uint8Array).prototype`.

Then I had a look at the source code of the polyfill:
```
CreateMethodProperty(Reflect, 'getPrototypeOf', function getPrototypeOf(target) {
	// 1. If Type(target) is not Object, throw a TypeError exception.
	if (Type(target) !== "object") {
		throw new TypeError(Object.prototype.toString.call(target) + ' is not an Object');
	}
	// 2. Return ? target.[[GetPrototypeOf]]().
	return Object.getPrototypeOf(target);
});
```
Since high level JS is not exactly my area, I don't now whether problem is in the OL code (but then probably non polyfill browsers would have problems) or in `Reflect.getPrototypeOf` polyfill code.

**Comment by JakeChampion** [comment]
Hi can you please post the full user agent for the browser you saw the issue with and also the full polfill.io URL or full polyfill list given to polyfill-library - with that information we should hopefully be able to help

**Comment by TomazicM** [comment]
My use agent is IE11 on Windows 10:
- `Version 21H1 (OS Build 19043.1348)`

This is the polyfill pack I use:
-  `https://polyfill.io/v3/polyfill.js?features=Symbol%2CPromise%2CObject.assign%2CElement.prototype.classList%2CEvent%2CReflect%2CReflect.getPrototypeOf%2CReflect.getOwnPropertyDescriptor%2CReflect.setPrototypeOf%2CReflect.set%2CReflect.preventExtensions%2CReflect.ownKeys%2CReflect.isExtensible%2CReflect.has%2CReflect.get%2CReflect.deleteProperty%2CReflect.defineProperty%2CReflect.construct%2CReflect.apply`

Here is the full HTML/JS code:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.9.0/css/ol.css">
    <style>
      html, body {
        height: 100%;
        padding: 0;
        margin: 0;
        background-color: white;
      }
      .map {
        height: 100%;
        width: 100%;
      }
    </style>
    <script src="https://polyfill.io/v3/polyfill.js?features=Symbol%2CPromise%2CObject.assign%2CElement.prototype.classList%2CEvent%2CReflect%2CReflect.getPrototypeOf%2CReflect.getOwnPropertyDescriptor%2CReflect.setPrototypeOf%2CReflect.set%2CReflect.preventExtensions%2CReflect.ownKeys%2CReflect.isExtensible%2CReflect.has%2CReflect.get%2CReflect.deleteProperty%2CReflect.defineProperty%2CReflect.construct%2CReflect.apply"></script>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.9.0/build/ol.js"></script>
    <title>Test</title>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script type="text/javascript">      
      var osmLayer = new ol.layer.Tile({
        source: new ol.source.OSM(),
      });
      
      var view = new ol.View({
        center: ol.proj.fromLonLat([14.6, 46]),
        zoom: 9
      });
                  
      var map = new ol.Map({
        layers: [osmLayer],
        target: 'map',
        view: view
      });     
    </script>
  </body>
</html>
```
This is the error I get in IE11:

> SCRIPT5022: Exception thrown and not caught
> polyfill.js (1838,3)

If I download polyfill pack in IE11 and then use it unconditionally in Chrome, Edge of Firefox, I get the same error. For example. this is the error I get in Edge (Version 96.0.1054.34 (Official build) (64-bit)):

> is.mjs:19 
> Uncaught TypeError: Cannot read properties of undefined (reading 'get')
>     at Object.5372 (is.mjs:19)
>     at r (bootstrap:19)
>     at startup:5
>     at startup:5
>     at universalModuleDefinition:9
>     at universalModuleDefinition:1

**Comment by mhassan1** [comment]
I don't think this problem is related to the `Reflect.getPrototypeOf` polyfill; I think it's a problem with `Symbol.toStringTag`. If I polyfill `Symbol.toStringTag` in modern Chrome, I get the same `Cannot read properties of undefined (reading 'get')` error.

I also see this when I polyfill `Symbol.toStringTag` only:
```js
const test = document.createElement('button')
test[Symbol.toStringTag] // -> undefined
```

I don't know enough about `Symbol`s to say what the problem is. Maybe related? https://github.com/zloirock/core-js/issues/890 or https://github.com/zloirock/core-js/issues/378 or https://github.com/inspect-js/which-typed-array/issues/46

**Comment by mhassan1** [comment]
It seems like we should be polyfilling `Symbol.toStringTag` on different prototypes, like this: https://github.com/inexorabletash/polyfill/blob/716a3f36ca10fad032083014faf1a47c638e2502/es6.js#L2329

**Comment by mhassan1** [comment]
I just added https://github.com/Financial-Times/polyfill-library/pull/1187, which adds `Symbol.toStringTag` to several prototypes; however, I don't think it actually solves this issue.

I think the problem is actually with IE11's implementation of `Uint8Array`, since it does not properly inherit from a `TypedArrayPrototype`:
```js
Object.getPrototypeOf(Uint8Array) === Object.getPrototypeOf(Object)
// (IE11) -> true
// (Chrome) -> false
```

The `ArrayBuffer` polyfill provided by `polyfill-library` does not replace the already existing `Uint8Array` implementation in IE11: https://github.com/inexorabletash/polyfill/blob/master/typedarray.js#L938

In order to fix the prototype chain issue, we would need to modify the `ArrayBuffer` polyfill to replace the `Uint8Array` implementation. What do you think, @JakeChampion?

**Comment by JakeChampion** [comment]
> In order to fix the prototype chain issue, we would need to modify the `ArrayBuffer` polyfill to replace the `Uint8Array` implementation. What do you think, @JakeChampion?

Thank you for looking into this, yes I agree that's what we should do 👍
