### ISSUE TITLE
`localStorage` polyfill allows overwriting methods

### ISSUE THREAD

**Issue by mhassan1** [Financial-Times/polyfill-library#1142]
## What
The `localStorage` polyfill allows overwriting its methods (e.g. `getItem`)

## Details
Reproduction Steps:
* Load `localStorage` polyfill
* Execute `localStorage.setItem('getItem', 'hello')`
* Execute `localStorage.getItem('getItem')`

Expected Result: `'hello'`
Actual Result: `Error: Function expected`

Browser: IE 7

**Comment by JakeChampion** [comment]
We changed our browser support a few years ago to only go as far back as IE 8, I think we don't actually need the localStorage polyfill anymore as it is configured only for IE 6 and 7.

I see we haven't documented the baseline supported versions in this repo, this is what they are:
```
        "edge": "*", # all versions
        "edge_mob": "*",  # all versions
        "ie": "8",
        "ie_mob": "11",
        "chrome": "29",
        "safari": "9",
        "ios_saf": "9",
        "ios_chr": "9",
        "firefox": "38",
        "firefox_mob": "38",
        "android": "4.3",
        "opera": "33",
        "op_mob": "10",
        "op_mini": "5",
        "bb": "6",
        "samsung_mob": "4"
```

That list comes from https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/3c0fbc4410f539922d520d7ae8b1632f128a69e3/data.json#L6-L23

**Comment by mhassan1** [comment]
Thanks. Since this is no longer a supported polyfill, I'll close this issue.
