### ISSUE TITLE
Unsupported polyfills should be removed

### ISSUE THREAD

**Issue by mhassan1** [Financial-Times/polyfill-library#1143]
## What
There are a few no longer needed polyfills that can be removed.

## Details
Legacy browser support has moved up ([link](https://github.com/Financial-Times/polyfill-library/issues/1142#issuecomment-989774035)), making some polyfills obsolete:
* `localStorage`
* `Window`
* `JSON`

We should remove these polyfills so we can stop maintaining them.

**Comment by mhassan1** [comment]
@JakeChampion Is there a good way for us to identify which polyfills can be removed? For example, can we query all config files for browser ranges that don't overlap with the supported set?

**Comment by romainmenke** [comment]
Removing it would technically be a breaking change for the polyfill-library.
Maybe marking them for deletion in a next major version would be best?

**Comment by mhassan1** [comment]
I've created a new issue for discussion of the next major: https://github.com/Financial-Times/polyfill-library/issues/1144
