### ISSUE TITLE
RFC : Use mdn compat table data instead of custom configuration

### ISSUE THREAD

**Issue by jdeniau** [Financial-Times/polyfill-library#1160]
## What

RFC to use the up-to-date [@mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) instead of local configuration (on at least use it to create such configuration)

## Details

In order to fix #1158 , I submitted #1159. In order to know which version of Opera should be added, I looked on mdn to see the browser compatibility.

I looked at #1042  and #19 that explain that you relly on automated tests, but some browsers are not really tested if I understood correctly. Moreover theses issues are quite old now.

I think it could be a good idea to use the mdn compatibility table.

Regarding the [Reflect API on mdn](https://github.com/mdn/browser-compat-data/blob/main/javascript/builtins/Reflect.json) and the [polyfill configuration](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Reflect/apply/config.toml), it seems quite easy to convert from mdn to polyfill.

## Additional information

I can try to work on that if this is relevant, but I would like your insight as I do not have your understanding of the project.

## Possible non-compatibility

It seems that data in mdn does not contain opera mobile or blackberry browser

**Comment by romainmenke** [comment]
@jdeniau I've added a new command `npm run lint-config` which is able to give feedback on configs with missing browsers like Opera.

I hope that this will make it easier to manually update configs when needed.
