### ISSUE TITLE
Bug: minified version of Function.prototype.name feature detect is incorrect

### ISSUE THREAD

**Issue by falconmick** [Financial-Times/polyfill-library#117]
The feature detect for Function.prototype.name is this:
```'name' in Function.prototype && (function x() {}).name === 'x'```
but when minified it is turned into this:
```"name"in Function.prototype&&"x"===function(){}.name```
which is incorrect because `"x"===function(){}.name` will always evaluate to false.

>Pollyfills used: polyfill.js?features=default,es6
>Pollyfill with issue: Object.defineProperty
>
>stack trace:
>
>```
>defineProperty | @ | polyfill.js?features=default,es6:414
>-- | -- | --
>defineProp | @ | polyfill.js?features=default,es6:414
>(anonymous function) | @ | app.js:1
>```
>
>I have a library somwhere inside one of my 1 million NPM packages that is trying to defined the property items ontop of an empty array (basically Object.defineProperty([], "items", config)) however the issue is ONLY happening on iOS 8, every other browser is fine with it. For this reason I am unable to figure out which of the million packages is doing this as I browserstack for whatever reasons is having a bad day when it comes to sourcemaps.
>
>This is making it so that I have 0 idea what is causing this error so I cannot just remove the package which is doing this and move on. All that being said, is it correct behaviour for the pollyfill service to fix this? I can't even tell if pollyfill.js is pollyfilling my browser :(
>
>I know this is a useless issue submission with very little info but I'm really at my witts end and this is basically just a cry for help. I am just hoping sombody has seen this before and knows a way to fix it. I'm hoping that it's not that I'm stuck and that theres somthing stupid I need to fix.
>
>Sorry.

**Comment by JakeChampion** [comment]
Hi @falconmick, sorry for taking so long to get to this issue.

We would need some more information to be able to help, such as the useragent string of the browser which has this issue and a reproducible test hosted on something like jsbin.com.

Hopefully the new version of polyfill.io has already solved this issue for you 🤞

**Comment by rmja** [comment]
@JakeChampion we are having this issue too. Here are the request details from the device that is failing:

![image](https://user-images.githubusercontent.com/2112306/55476245-5eb99280-5616-11e9-97d3-120c349d10d6.png)

And some console output:
![image](https://user-images.githubusercontent.com/2112306/55476287-81e44200-5616-11e9-949a-cb7d95df058a.png)


The device is an iPad Air 2

**Comment by rmja** [comment]
Here are some line numbers in the non-minified polyfill

![image](https://user-images.githubusercontent.com/2112306/55476525-1f3f7600-5617-11e9-9aad-3314d5acfdf7.png)

**Comment by JakeChampion** [comment]
Hi @rmja, thanks for the comments, could you please post the url and headers as text so that I can copy them into some test files?

**Comment by rmja** [comment]
Sure thing.

Request Url: https://polyfill.io/v3/polyfill.js?features=default,es6,fetch,Intl,Intl.~locale.da,Intl.~locale.de,Intl.~locale.en

Request headers:
```
Accept:*/*
Cache-Control:max-age=0
If-None-Match:W/"18f93-ZhGf9BuHLP3keaWRGXoWlIPh63U"
Origin:http://192.168.1.146:5757
Referer:http://192.168.1.146:5757/new-booking
User-Agent:Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H143 Safari/600.1.4
```

Response headers:
```
Access-Control-Allow-Methods:GET,HEAD,OPTIONS
Access-Control-Allow-Origin:*
Age:693
Cache-Control:public, s-maxage=31536000, max-age=604800, stale-while-revalidate=604800, stale-if-error=604800
Connection:keep-alive
Date:Wed, 03 Apr 2019 11:58:57 GMT
ETag:W/"18f93-ZhGf9BuHLP3keaWRGXoWlIPh63U"
Server-Timing:HIT, fastly;desc="Edge time";dur=2
Vary:User-Agent, Accept-Encoding
```

We just hit this issue resently, and I am currently trying to dig into it

**Comment by rmja** [comment]
This is the line that is causing the issue:

![image](https://user-images.githubusercontent.com/2112306/55477374-2ebfbe80-5619-11e9-849c-12194699c933.png)

**Comment by rmja** [comment]
@JakeChampion let me know if there is anything else I can do to resolve the issue...

**Comment by JakeChampion** [comment]
The bug looks to be in the minifier!
The feature detect for Function.prototype.name is this:
```
'name' in Function.prototype && (function x() {}).name === 'x'
```
but when minified it is turned into this:
```
"name"in Function.prototype&&"x"===function(){}.name
```

which is incorrect because `"x"===function(){}.name` will always evaluate to false.

I will look into this right away!

**Comment by rmja** [comment]
But I am not requesting the minified version (at least here). The error also occurs on the site when loading the non-minified version.

**Comment by JakeChampion** [comment]
The feature detects are always served minified.

PR for this work is https://github.com/Financial-Times/polyfill-library/pull/181

**Comment by rmja** [comment]
... and the error still shows up when I disable feature detection by adding `&flags=always` to the request url.

**Comment by JakeChampion** [comment]
@rmja, the symptom you are seeing is that the polyfill will not work in browsers which already support the feature. The reason that happens for your original request is because the user-agent is detected as one we do not support and so we serve it all the requested polyfills and put them behind feature detects however, the feature detects are served in a minified format and the minifier was not preserving the function names, which made the feature detect for function.prototype.name support always return false , even for browsers which do support function.prototype.name.

**Comment by JakeChampion** [comment]
This has been released in https://github.com/Financial-Times/polyfill-library/releases/tag/v3.33.0

**Comment by brunohstein** [comment]
@JakeChampion, I'm still seeing this `TypeError`. I'm testing on an old Firefox version (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:29.0) Gecko/20100101 Firefox/29.0`).

It looks like what was supposed to be `"x"===function x(){}.name` is being compiled to `"x"===function n(){}.name`.

![Screenshot 2019-05-07 13 26 09](https://user-images.githubusercontent.com/1143565/57316238-b3e03c80-70cb-11e9-8a45-8aa064bc4417.png)

**Comment by JakeChampion** [comment]
I can confirm that this still exists, such a shame that the option to preserve function names with UglifyJS is not working correctly

**Comment by rmja** [comment]
I think it works, the problem is that the new version is not available yet on polyfill.io

**Comment by rmja** [comment]
It runs 3.31.1 and this is fixed in 3.33.0

**Comment by JakeChampion** [comment]
I think we released a new polyfill-service which uses the latest polyfill-library --> https://github.com/Financial-Times/polyfill-service/blob/master/package.json#L48

**Comment by rmja** [comment]
https://polyfill.io/v3/polyfill.js shows 3.31.1 in the top

**Comment by JakeChampion** [comment]
You likely need to do a hard refresh in your browser to get the latest version @rmja

**Comment by rmja** [comment]
Strange, tt seems as if the gzip and br compressed versions are not updated.

This:
```
curl 'https://polyfill.io/v3/polyfill.js' -H 'authority: polyfill.io' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'sec-fetch-dest: document' -H
 'sec-fetch-site: cross-site' -H 'sec-fetch-user: ?F' -H 'sec-origin-policy: 0' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'referer: https://github.com/Financial-Times/polyfill-library/issues/117' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: da-DK,da;q=
0.9,en-US;q=0.8,en;q=0.7' --compressed | brotli --decompress
```
returns 
```
/* Polyfill service v3.31.1
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 *
 * Features requested: default
 *  */


/* No polyfills found for current settings */
```

But, with the `Accept-Encoding` header removed:
```
curl 'https://polyfill.io/v3/polyfill.js' -H 'authority: polyfill.io' -H 'pragma: no-cache' -H 'cache-control: no-cache' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'sec-fetch-dest: document' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-user: ?F' -H 'sec-origin-policy: 0' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'referer: https://github.com/Financial-Times/polyfill-library/issues/117' -H 'accept-language: da-DK,da;q=0.9,en-US;q=0.8,en;q=0.7'
```

i get:
```
/* Polyfill service v3.34.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 *
 * Features requested: default
 *  */


/* No polyfills found for current settings */
```

**Comment by JakeChampion** [comment]
This is now fixed
