### ISSUE TITLE
Array.from(Set.values()) causes exception in IE11

### ISSUE THREAD

**Issue by ZebraFlesh** [Financial-Times/polyfill-library#119]
Straight forward to reproduce:

1. Go to https://polyfill.io/v2/docs/ in IE11
2. Open up the console
3. Execute the statement `Array.from(new Set([1, 1, 2, 2, 3]).values())`
4. Observe the exception `Unable to get property '0' of undefined or null reference`.  This seems to be coming from the [makeIterator function used to polyfill Set.prototype.values](https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Set/polyfill.js#L21).

Why would you want to make such a call? If you have an array of values, tossing them into a set is an easy way to dedupe them.

Call stack from unminified polyfill.js (v3.23.0):
```
next - polyfill.js (3358, 12)
parseIterable - polyfill.js (2317, 5)
parseIterableLike - polyfill.js (2463, 3)
from - polyfill.js (2497, 4)
```

Seems like this might be related to #1293 ?

**Comment by JakeChampion** [comment]
It looks like this has been fixed in recent versions of polyfill-library and polyfill.io
![bs_win10_ie_11 0 2](https://user-images.githubusercontent.com/1569131/53186414-dbf5ee80-35f8-11e9-9d34-9357d16690fc.jpg)
