### ISSUE TITLE
Unhandled Rejection (TypeError): fs$readdir is not a function

### ISSUE THREAD

**Issue by param-kothari** [Financial-Times/polyfill-library#1191]
This is a bug report, or rather, we needed some help to resolve this issue regarding the usage of polyfill-library.

## What

We faced an issue while installing and using the polyfill library. Upon installing, we tried to use the library with the following code, taking inspiration from this comment -> [Link](https://github.com/Financial-Times/polyfill-library/issues/479#issuecomment-590315068)

```
const polyfillLibrary = require('polyfill-library');

const polyfillBundle = polyfillLibrary.getPolyfillString({
	minify: true,
	unknown:'polyfill'
	features: {
		'all': { flags: ['gated'] }
	}
}).then(function(bundleString) {
	fs.writeFileSync('polyfill-all.js', bundleString, 'utf-8');
});
```

However, we are facing two errors for this: `Unhandled Rejection (TypeError): fs$readdir is not a function` and `Unhandled Rejection (TypeError): fs$readFile is not a function`. Upon digging deeper, we found that this could be an issue with `graceful-fs` where the imported `fs` module doesn't contain the readdir and readFile methods.

Also, in the package.json file for graceful-fs, the files list include `fs.js` whereas it's not present in the dir. So, we think that there could be an issue related to that.

## Details

- The expected behaviour is that the polyfills should be generated, but instead, we are getting the two errors mentioned above.
- This is occurring for us directly upon normal installation and usage of the library as described in the docs.
- Environment: Chrome 101.0.4951.64, macOS (laptop)
- nvm version used for installation: v14.17.5

<img width="1113" alt="Screen Shot 2022-05-26 at 1 12 01 AM" src="https://user-images.githubusercontent.com/41911452/170354245-3c934ffc-2579-4360-9bd0-295ece81b0fb.png">
<img width="1174" alt="Screen Shot 2022-05-26 at 1 12 20 AM" src="https://user-images.githubusercontent.com/41911452/170354268-299fb960-943b-4304-9ac5-5021d0de6a3c.png">

Not sure if this issue is related to the following one, but I'm attaching a link just in case -> #479

**Comment by JakeChampion** [comment]
Polyfill-library does not work in a browser context which is why this issues happens

**Comment by param-kothari** [comment]
Thanks, got the issue
