### ISSUE TITLE
can't install polyfill-library successfully

### ISSUE THREAD

**Issue by panxiaomeng** [Financial-Times/polyfill-library#1195]
hi, it is support request
I run these commands in the server, I can't see these issues, but I can see some errors in the container, 
npm install
npm install run-s -D
npm run build

when I run npm isntall in the container, it prints below error firstly

_npm WARN tarball tarball data for polyfill-library@3.104.0 (sha512-sYbO07WkGKSub4HxUKK/8eYSxV/HS4xOUcexmV/zBl6Ma2JJypKWk1xgbcZi2Gs4CmPrZIpfGhdPK1aFXjJKtQ==) seems to be corrupted. T
rying one more time.
npm ERR! code EBUSY
npm ERR! syscall unlink
npm ERR! path /mountdir/310e23f6-7178-4be1-86c2-11d7635e45ea/polyfill-service/backend-services/polyfill-service/node_modules/.staging/polyfill-library-3ad430e8/polyfills/__dist/Intl
.DisplayNames.~locale.ar-SY/.nfs0000000092386a0e00000098
npm ERR! errno -16
npm ERR! EBUSY: resource busy or locked, unlink '/mountdir/310e23f6-7178-4be1-86c2-11d7635e45ea/polyfill-service/backend-services/polyfill-service/node_modules/.staging/polyfill-lib
rary-3ad430e8/polyfills/__dist/Intl.DisplayNames.~locale.ar-SY/.nfs0000000092386a0e00000098'_

then I googled this issue, and I found a solution, that is adding "npm cache clean --force".

after that no such issue happened, but when I run command npm run build, it prints below issue.

no such file or directory, open '/mountdir/2d5736a1-1624-42e9-8e46-1ec0dda24af1/polyfill-service/backend-services/polyfill-service/node_modules/polyfill-library-3.27.4/polyfills/__dist/aliases.json

then I install this version again by command "npm install polyfill-library-3.28.1" and "npm install polyfill-library-3.27.4". 

then it looks ok. 

finally I deployed this in the kubernetes, and then the service can't be up, 
the log says 
Started worker 119
Warning: metrics are not being recorded for this application. Please provide a FT_GRAPHITE_APP_UUID environment variable
Warning: errors are not being logged to Sentry for this application. Please provide a SENTRY_DSN environment variable
polyfill-service configured (graphite=false logging=true sentry=false)
**No polyfill sources found.  Run `npm run build` to build them**

could you please help have a look, what should I do?

**Comment by romainmenke** [comment]
@panxiaomeng Can you describe at a higher level what you are aiming to do?

From your bug report it seems as if you are trying to build the `polyfill-library` but also run your own version of `polyfill-service`.

Can you share the `Dockerimage` you are using?
