### ISSUE TITLE
ArrayBuffer.isView Edge data

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1203]
https://github.com/Financial-Times/polyfill-library/blob/de90e2e0678f1daacdac4d931d1d8b5501353901/polyfills/ArrayBuffer/isView/config.toml#L13

@mhassan1 Do you remember why this is `edge <12` ?
Edge 12 is the first edge versions so this would never match anything.

Is it a typo or was the intention to not server the polyfill to edge?

**Comment by romainmenke** [comment]
Maybe this was copied over from other configs? (which are also a bit suspect)

https://github.com/Financial-Times/polyfill-library/commit/9b345f4b9d0f223f003ae0f6d936a2eabcc7a314

**Comment by mhassan1** [comment]
In this case, I believe I just took what was on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView#browser_compatibility), without realizing that 12 was the first version.

**Comment by romainmenke** [comment]
Ah yes! makes sense :)
Thank you
