### ISSUE TITLE
Use the baseline versions from the UA normaliser in config linting

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1205]
baseline : https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/data.json#L7-L22

see : https://github.com/Financial-Times/polyfill-library/pull/1204

Some version ranges have a lower bound that is less than the baseline. `2 - 50`
We can simplify these to `<51` as that is how they already function today.

The config linter should be updated to suggest the needed edits

**Comment by romainmenke** [comment]
The baseline is fairly high for some browsers like Safari :
- Safari 9 was only released in 2016 (6 years ago).
- IE 9 was released in 2011 (11 years ago).

Removing support stats based on the UA normaliser baseline will affect packages like core-web that bring their own logic.

@JakeChampion Is there a downside to keeping support stats for older browsers that do not meet the baseline? Something that affects the library or service?

If not I would prefer to keep these stats.

**Comment by JakeChampion** [comment]
> Removing support stats based on the UA normaliser baseline will affect packages like core-web that bring their own logic.
> 
> @JakeChampion Is there a downside to keeping support stats for older browsers that do not meet the baseline? Something that affects the library or service?
> 
> If not I would prefer to keep these stats.

Could you explain what you mean by this as unfortunately I don't understand 😔

**Comment by romainmenke** [comment]
https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Promise/prototype/finally/config.toml#L14-L25

`Promise.prototype.finally` is a good example.
It has a specific range that doesn't overlap with `Promise`.
This range also includes browsers that no longer meet the UA normaliser baseline.

The idea in this issue (based on the PR comment) was to transform configs in this style :

```diff
[browsers]
bb = ">10"
chrome = "32 - 63"
edge = "13 - 17"
edge_mob = "13 - 17"
- firefox = "29 - 57"
+ firefox = "<57"
- firefox_mob = "29 - 57"
+ firefox_mob = "<57"
- opera = "19 - 50"
+ opera = "<50"
op_mob = "19 - 46"
- safari = "8.0 - 11.1"
+ safari = "<11.1"
- ios_saf = "8.0 - 11.3"
+ ios_saf = "<11.3"
- samsung_mob = "3 - 7.4"
+ samsung_mob = "<7.4"
```

But other users (like core-web) can use the same data and decide to support much older browsers than the [UA normaliser baselines](https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/data.json#L7-L22).

**Comment by JakeChampion** [comment]
> But other users (like core-web) can use the same data and decide to support much older browsers than the [UA normaliser baselines](https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/data.json?rgh-link-date=2022-08-03T12%3A55%3A33Z#L7-L22).
> 
> So I am leaning towards keeping the support stats as correct as possible regardless of the UA normaliser baselines. (but I am biased here)

That seems like a good reason to keep them as specific as can be 👍

**Comment by romainmenke** [comment]
Cool cool :)
