### ISSUE TITLE
IntersectionObserver Polyfill Out-of-Date

### ISSUE THREAD

**Issue by worsnupd** [Financial-Times/polyfill-library#122]
Looks like there have been changes with the [official IntersectionObserver polyfill](https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js) that are not-yet reflected in Polyfill.io.

**Comment by biou** [comment]
IntersectionObserver is now supported by the latest versions of Safari on iOS and OSX.
https://caniuse.com/#search=intersectionobserver
