### ISSUE TITLE
Why would this polyfill library stops to polyfill old browsers?

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1226]
Why would this polyfill library stops to polyfill old browsers? 😂

_Originally posted by @noscripter in https://github.com/Financial-Times/polyfill-library/issues/1153#issuecomment-1220332053_

---------

Context : removing polyfills for IE8

**Comment by romainmenke** [comment]
Hi @noscripter,

Thank you for reaching out.
I've moved this to a separate issue because this is a bit clearer than a merged and closed pull request.

---------

IE8 in particular was lacking so many features that it was always very difficult to create correct polyfills for it.

Periodically removing support for the very oldest browsers "unlocks" more modern features that can be used to create polyfills.

This also keeps the project a bit more maintainable but that is a secondary concern.

In this case IE8 was dropped so that we can now assume that all supported browsers have `Object` getters and setters. This results in smaller, cleaner polyfills with fewer differences versus the native feature.

------

Was there any issue in particular that this update is causing on your end?

**Comment by noscripter** [comment]
Thanks for your explanation, that's totally understandable and reasonable.

Documentation should be upgraded accordingly so as to clarify version differences.

Greatly appreciated for your excellent work!👍

**Comment by romainmenke** [comment]
> Documentation should be upgraded accordingly so as to clarify version differences.

Can you link to the documentation that is outdated or unclear?
( There are a lot of moving parts here :) )

At this time only this repo has been updated but this change hasn't yet rolled out on polyfill.io.
