### ISSUE TITLE
Polyfill fails in IE11 when using Array.from of a Map

### ISSUE THREAD

**Issue by devuxer** [Financial-Times/polyfill-library#124]
Normally, applying `Array.from` to a JavaScript `Map` results in an array of `[key, value]` tuples. However, when using polyfill.io with default features in IE11, it results in an array of `undefined`.

Here is a repro:

```javascript
var fooMap = new Map()
  .set("key1", "value1")
  .set("key2", "value2");

var fooKeys = Array.from(fooMap.keys());
console.log("first key", fooKeys[0]); // works fine

var fooPairs = Array.from(fooMap);
console.log("first pair", fooPairs[0]); // in IE11, results in an array of undefined instead of key/value tuples
```

Please see this [CodePen](https://codepen.io/devuxer/pen/PmgYjY?editors=1111) for a live demo of the problem.

**Comment by JakeChampion** [comment]
This looks to have been fixed in recent releases of the library.

![bs_win10_ie_11 0 4](https://user-images.githubusercontent.com/1569131/53188264-e4e8bf00-35fc-11e9-82f0-9bed46af8601.jpg)
