### ISSUE TITLE
Issue on dependencies resolution

### ISSUE THREAD

**Issue by JSteunou** [Financial-Times/polyfill-library#125]
I think there is an issue on the dependencies resolution, enlighten in last Chrome, around Iterator.

See this https://polyfill.io/v2/polyfill.js?features=default,es6,es7 in Chrome 61 for example.

```
/* Polyfill service v3.21.3
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * UA detected: chrome/61.0.0
 * Features requested: default,es6,es7
 * 
 * - Array.prototype.values, License: MIT (required by "es6")
 * - _Iterator, License: MIT (required by "_ArrayIterator", "Array.prototype.@@iterator", "Array.prototype.values", "es6")
 * - String.prototype.contains, License: CC0 (required by "_ArrayIterator", "Array.prototype.@@iterator", "Array.prototype.values", "es6")
 * - _ArrayIterator, License: MIT (required by "Array.prototype.@@iterator", "Array.prototype.values", "es6") */

...

and this goes on with polyfills for Array.prototype.values, _Iterator, _ArrayIterator, String.prototype.contains
```

If we look at `Array.prototype.values` it actually should be polyfilled in Chrome 61, the statement is correct. It depends on [`Array.prototype.@@iterator` and `Symbol.iterator`](https://github.com/Financial-Times/polyfill-service/blob/v3.22.0-0/polyfills/Array/prototype/values/config.json) which depends on `_ArrayIterator`

Looking back at the polyfill generated, the header tells us that `_Iterator` and `_ArrayIterator` are included because of `Array.prototype.values` which is a falsy statement.

The entire chain is `Array.prototype.values` --> `Array.prototype.@@iterator` --> `_ArrayIterator` --> `_Iterator` and this chain should be broke at `Array.prototype.@@iterator` with Chrome 61 because [it supports it](https://github.com/Financial-Times/polyfill-service/blob/v3.22.0-0/polyfills/Array/prototype/%40%40iterator/config.json).

This make polyfill-service include more useless stuff, and some cannot be gated.

**Comment by JakeChampion** [comment]
Fixed via https://github.com/Financial-Times/polyfill-library/pull/558 and confirmed fixed via https://github.com/Financial-Times/polyfill-library/pull/622
