### ISSUE TITLE
Symbol.for() not returning identical value on both sides of iframe

### ISSUE THREAD

**Issue by KevinBrogan** [Financial-Times/polyfill-library#126]
Test Case: https://jsbin.com/wogulatinu/edit?js,console
ie11: polyfill is used, result is false.
chrome: polyfill not used, result is true.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for
https://www.ecma-international.org/ecma-262/6.0/#sec-symbol.for

**Comment by JakeChampion** [comment]
It is not possible to polyfill Symbol.for and Symbol.keyFor in a way that works across realms/iframe boundaries.

If you need cross-realm support, you can only use the native Symbol implementations
