### ISSUE TITLE
Object.hasOwn

### ISSUE THREAD

**Issue by nicksrandall** [Financial-Times/polyfill-library#1262]
Feature Request: Object.hasOwn polyfill

## What
I'd love if this library had a polyfill for Object.hasOwn

Example polyfill:
https://github.com/es-shims/Object.hasOwn

**Comment by romainmenke** [comment]
This polyfill exists : https://github.com/Financial-Times/polyfill-library/tree/master/polyfills/Object/hasOwn

So it should be possible to use it from the library.
