### ISSUE TITLE
IntersectionObserverEntry is not targeting older Operas/Chrome 51 until Chrome 57

### ISSUE THREAD

**Issue by christianhaller3000** [Financial-Times/polyfill-library#1282]
https://github.com/Financial-Times/polyfill-library/blob/c7a1de7d89d85da981c6fe1ca4e0f7c24b0cc35b/polyfills/IntersectionObserverEntry/config.toml#L8

Hi, older Chromes/Operas have only the partial support for the IntersectionObserver.

![Bildschirm­foto 2023-03-21 um 18 39 12](https://user-images.githubusercontent.com/42344734/226695252-b8bbfefc-af0c-4f03-a5fd-011ec615f603.png)

https://caniuse.com/intersectionobserver

the config for IntersectionObserverEntry is only targeting Microsoft Edge.

**Comment by romainmenke** [comment]
A fix for this issue was released in [`v4.8.0`](https://github.com/Financial-Times/polyfill-library/releases/tag/v4.8.0)

Thank you again for reporting this!
