### ISSUE TITLE
BUG: Polyfill produce an Unhandled Promise Rejection in lambda v18 AWS

### ISSUE THREAD

**Issue by RodrigoTomeES** [Financial-Times/polyfill-library#1291]
## What

We are using Polyfill.io wit NextJS and Serverless. First we create a API in NextJS that return our polyfills.

```ts
import polyfillLibrary from 'polyfill-library';

import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const polyfillBundle = await polyfillLibrary.getPolyfillString({
    uaString: req.headers['user-agent'],
    minify: true,
    features: {
      structuredClone: { flags: ['gated'] },
      'Array.prototype.at': { flags: ['gated'] },
    },
  });
  const buf = Buffer.from(polyfillBundle.toString(), 'utf-8');

  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/javascript');
  res.setHeader('Content-Length', buf.byteLength);
  res.end(buf);
}
```

This works as expected in local but when we deploy it in AWS Lambdas access to that API produce a Unhandled Promise Rejection, you can see the entire error in the next lines.

```bash
2023-05-13T08:11:03.684Z	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: ENOENT: no such file or directory, scandir '/var/task/polyfills/__dist'",
    "reason": {
        "errorType": "Error",
        "errorMessage": "ENOENT: no such file or directory, scandir '/var/task/polyfills/__dist'",
        "code": "ENOENT",
        "errno": -2,
        "syscall": "scandir",
        "path": "/var/task/polyfills/__dist",
        "stack": [
            "Error: ENOENT: no such file or directory, scandir '/var/task/polyfills/__dist'"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, scandir '/var/task/polyfills/__dist'",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)",
        "    at process.emit (node:events:513:28)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```

## Details

Expected behaviour: The API endpoind should work like in local.
Actually happening: The API endpoind throw an Unhandled Promise Rejection

Steps to reproduce:

- Create a NextJS template (we are in NextJS 12.3.4)
- Create an API with the provided code
- Deploy it using [Serverless NextJS](https://github.com/serverless-nextjs/serverless-next.js)

## Additional information

Headers provided by Cloudfront. We know we have another issue becase cloudfront always provide the same User Agent but that is because we don't configurate properly Cloudfront. 

```bash
2023-05-13T08:11:03.603Z	INFO	req.headers {
  host: 'd2um352p097y7m.cloudfront.net',
  cookie: 'PHPSESSID=',
  'x-forwarded-for': 'xx.xx.xx.xx,
  'user-agent': 'Amazon CloudFront',
  via: '2.0 xxxxx.cloudfront.net (CloudFront)',
  'accept-encoding': 'gzip',
  dnt: '1',
  'upgrade-insecure-requests': '1',
  'sec-fetch-dest': 'document',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-site': 'none',
  'sec-fetch-user': '?1'
}
```

**Comment by JakeChampion** [comment]
@RodrigoTomeES thanks for the issue - It looks to me like this project's code is being bundled together before uploading to AWS Lambda, if that's the case, the bundler needs to also include all the built polyfills - they are not "require"d or "import"ed in polyfill-library, they are erad as files via `fs`, which is something some bundlers are not going to include in their bundle by default. You will likely need to program the bundler to include the polyfill-library/polyfills/__dist folder verbatim. Saying all this, I actually don't believe we have built polyfill-library to work when bundled, so that may not work but is perhaps worth a shot. If it doesn't work, could you create a small reproducible example for the polyfill.io team to work with?

**Comment by RodrigoTomeES** [comment]
@JakeChampion Hi, thanks, I will investigate how to include that files in our bundle. In the other hand here is the minimal reproduction [codesandbox](https://codesandbox.io/p/github/RodrigoTomeES/bug-nextjs-api-polyfill) and [github](https://github.com/RodrigoTomeES/bug-nextjs-api-polyfill).

**Comment by RodrigoTomeES** [comment]
@JakeChampion hi, I included all polyfills in the lambda but the error continue. I think I need to change the folder that polyfill.io request that files (I think root var isn't avaliable in the lambda, I add the var directory in lambda folder) but I didn't see how to make it.

**Comment by RodrigoTomeES** [comment]
Closed in favor of issue #1292.

**Comment by romainmenke** [comment]
@RodrigoTomeES The code in question in the library can be found here : https://github.com/Financial-Times/polyfill-library/blob/master/lib/sources.js#L11

`const polyfillDirectory = path.join(__dirname, "../polyfills/__dist");`

This is not an absolute path to `/var/..`
`__dirname` just happens to be `/var/task/` in your case.

To resolve your issue you must modify your script so that the `polyfills` directory is located in the same directory as your main entrypoint.

If your entrypoint is `index.js` :

```
index.js
polyfills
  __dist
    polyfill-a
    polyfill-b
    ...
```

**Comment by RodrigoTomeES** [comment]
@JakeChampion Yes, I found that code and I modify the polyfillDirectory to make it relative with this patch. And I use this post to make it https://dev.to/zhnedyalkow/the-easiest-way-to-patch-your-npm-package-4ece.

```diff
diff --git a/node_modules/polyfill-library/lib/sources.js b/node_modules/polyfill-library/lib/sources.js
index 1162671..ee66b70 100644
--- a/node_modules/polyfill-library/lib/sources.js
+++ b/node_modules/polyfill-library/lib/sources.js
@@ -8,7 +8,7 @@ const readdir = promisify(fs.readdir);
 const LRUCache = require('mnemonist/lru-cache');
 const polyfillMetaCache = new LRUCache(1000);
 const polyfillSourceCache = new LRUCache(1000);
-const polyfillDirectory = path.join(__dirname, "../polyfills/__dist");
+const polyfillDirectory = `.${path.join(__dirname, "../polyfills/__dist")}`;
 const stream = require('stream');
 
 /**
```

It's actually strange to me that serverless-next introduces the directory /var/task/ as __dirname because it doesn't exist in the Lambda. Could it be that it's where the bundler task is executed, and that's why that directory is shown? In that case, we might need to use a different method instead of calling __dirname. 🤔

**Comment by romainmenke** [comment]
fyi : I reopened this one because it contains the error message and a lot of reproduction details :)

I was still hoping that there was some way this could be resolved without making changes to the `polyfill-library`.

---------

> as __dirname because it doesn't exist in the Lambda.

These seem relevant : 
- https://stackoverflow.com/questions/51549209/aws-lambda-filesystem-path-for-a-serverless-framework-function
- https://github.com/serverless/serverless/issues/4778

If I understand these correctly Lambda has a path structure of `/var/task/src/your-entry-point.js`

`__dirname/../polyfills` would then be `/var/task/polyfills`, however nothing outside of `./src` is deployed.

> In your repo that /src directory (probably — if you are using the default Serverless project structure) contains your handler.js file and is the reference point (first directory to be copied in from your serverless project) from your Repo — nothing above that src directory is copied in.

If the `polyfill-library` didn't go up one level in the directory tree it might be possible to get this working.

correct?

**Comment by JakeChampion** [comment]
I think so, perhaps we could use `path.join(path.dirname(require.resolve("polyfill-library")), "../polyfills/__dist")` instead of `const polyfillDirectory = path.join(__dirname, "../polyfills/__dist");` and that'd solve the issue?

**Comment by RodrigoTomeES** [comment]
I will try the two methods @JakeChampion @romainmenke removing the up level and replacing __dir and I will let you if that works. Thanks!!

**Comment by RodrigoTomeES** [comment]
@romainmenke removing the .. the result is -> polyfillDirectory /var/task/chunks/polyfills/__dist
@JakeChampion using `path.join(path.dirname(require.resolve("polyfill-library")), "../polyfills/__dist")` instead of `const polyfillDirectory = path.join(__dirname, "../polyfills/__dist");` this throw a new error

```bash
2023-05-18T10:15:13.894Z	ERROR	Invoke Error 	{
    "errorType": "TypeError",
    "errorMessage": "The \"path\" argument must be of type string. Received type number (38756)",
    "code": "ERR_INVALID_ARG_TYPE",
    "stack": [
        "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type number (38756)",
        "    at new NodeError (node:internal/errors:399:5)",
        "    at validateString (node:internal/validators:163:11)",
        "    at Object.dirname (node:path:1276:5)",
        "    at 6162 (/var/task/chunks/617.js:6496:42)",
        "    at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)",
        "    at 38756 (/var/task/chunks/617.js:6078:17)",
        "    at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)",
        "    at 90384 (/var/task/pages/api/polyfills.js:177:74)",
        "    at __webpack_require__ (/var/task/webpack-api-runtime.js:25:43)",
        "    at 32103 (/var/task/pages/api/polyfills.js:157:23)"
    ]
}
``` 

Reviewing the links that @romainmenke  sent, I understood that /var/task is the working directory of the Lambda function. So, what I did was modify the file copying script to paste them directly into the root of src without including the /var/task directory, as this directory only exists during execution, resulting in /var/task/polyfill... and this way it works.

```js
import { copySync } from 'fs-extra/esm';

import { createDir } from '../bin/utils.mjs';

const DIR_POLYFILLS = './node_modules/polyfill-library/polyfills/__dist';
const DIR_SERVERLESS =
  './.serverless_nextjs/api-lambda/polyfills/__dist';

await createDir(DIR_SERVERLESS);

try {
  console.log('Copying polyfills to serverless directory...');
  copySync(DIR_POLYFILLS, DIR_SERVERLESS, { overwrite: false });
  console.log('Polyfills copied successfully!');
} catch (err) {
  console.error(err);
}
```

Therefore, I don't think any changes need to be made in this aspect. However, I do believe it would be good to include a section in the documentation discussing this topic and provide a script to copy the polyfills to the bundle directory, as [Partytown](https://partytown.builder.io/nextjs#copy-library-files) does.

I update the README talking about this, I hope this can be usefull #1293
