### ISSUE TITLE
[Request] Please add polyfill for reportValidity() - Constraint Validation API

### ISSUE THREAD

**Issue by ashucg** [Financial-Times/polyfill-library#131]
It would be great to have `reportValidity()` polyfill included. Right now I am using [reportValidity() ponyfill](https://github.com/jelmerdemaat/report-validity)

**Comment by underbyte** [comment]
Isn't this a duplicate of #29 ?

**Comment by ashucg** [comment]
@underbyte oops! yes, it is, my bad!
