### ISSUE TITLE
User Agent Parsing Cache

### ISSUE THREAD

**Issue by mridgway** [Financial-Times/polyfill-library#139]
## What

Performance regression in new polyfill-library.

## Details

The latest version of the polyfill-library has a regression in performance in comparison to an older version of the polyfill-service (3.25.1 is what I'm testing). 

When I looked into it, it seems that the polyfill-library no longer uses an LRU cache for the User Agent parsing (see https://github.com/Financial-Times/polyfill-service/blob/1f45e5b95625180117d5b2f1979d8e217bc791a4/packages/polyfill-library/lib/UA.js#L23 for the old implementation).

I see that `lru-cache` is still in the dependencies for polyfilly-library. Is it supposed to be used around the UA normalizer or was it intentional to not use an LRU cache any more?

I don't mind doing a PR if it is desirable to re-introduce the cache.

**Comment by JakeChampion** [comment]
We removed the lru-cache as not all users of this package require caching of the parsed user-agents. Have you seen a large performance regression since this was removed?

**Comment by mridgway** [comment]
Yes, we were seeing an average of around 5ms for full `getPolyfillString` prior to the upgrade. After upgrading our average was around 80ms with a lot more deviation.

One issue is that it doesn't seem we have access to the UA parsing to be able to cache it in userland, we would have to cache the full polyfill string which would be a very large memory requirement.

**Comment by JakeChampion** [comment]
I've made a PR to add back a fast lru cache --> https://github.com/Financial-Times/polyfill-library/pull/141
