### ISSUE TITLE
Cache fs `readFile` operations

### ISSUE THREAD

**Issue by bringking** [Financial-Times/polyfill-library#147]
Feature Request

## What

Thanks for the fantastic library. We are using this in production for a fairly high-traffic application. We are noticing in our APM that we are performing quite a few `readFile` operations. When diving in, we noticed they are mostly coming from Polyfill Library. This isn't causing a huge problem per-se, but it is introducing time into our request that I think can be reduced. 

## Details

Looking at the code here - 
https://github.com/Financial-Times/polyfill-library/blob/master/lib/sources.js#L16

It seems we could replace this with a simple `require` call (which is sync, but cached). Or stick with the readFile approach and cache the result. This would obviously mean the files can't be updated after the app boots, but that seems like an edge case. Is this something you guys have thought about? I would be happy to submit a PR.

**Comment by JakeChampion** [comment]
Thanks for opening this issue @bringking. I think we would want to go with a least-recently-used-cache (LRU-cache) instead of the synchronous require. I'll make a pull-request for this work now :-)

**Comment by bringking** [comment]
@JakeChampion I don't see that code change in the npm release, looks like the old code 🤔

**Comment by bringking** [comment]
@JakeChampion any idea when you might fix the release? Would love to get this out
