### ISSUE TITLE
Latest release 3.31 Missing Code

### ISSUE THREAD

**Issue by bringking** [Financial-Times/polyfill-library#152]
## What

The latest release 3.31 on NPM doesn't seem to contain the latest commits from master. 
## Details

The NPM package and the release tarball don't have the new code 😞

**Comment by JakeChampion** [comment]
I published 3.31.1 just now and it includes the changes 👍  https://unpkg.com/polyfill-library@3.31.1/lib/sources.js

Thanks for pointing out the previous release didn't include them :-)

**Comment by bringking** [comment]
@JakeChampion thank you sir!
