### ISSUE TITLE
IE 11 error: Object doesn't support this action

### ISSUE THREAD

**Issue by devuxer** [Financial-Times/polyfill-library#154]
I'm experiencing a perplexing error in Internet Explorer 11 (IE 11) when the following line is hit in [this script](https://polyfill.io/v3/polyfill.js?features=Promise,Object.assign,Object.getOwnPropertyDescriptor):

`var desc = Object.getOwnPropertyDescriptor(from, nextKey);`

The error is:

> SCRIPT445: Object doesn't support this action

It's not clear to me what object and action are being referred to in this message since `Object.getOwnPropertyDescriptor` has existed since IE 8.

I've pushed a [github repo](https://github.com/devuxer/reach-polyfills-issue) that reproduces this bug. Please see the README for additional details and screen captures from the debugger.

# Steps to reproduce:

1. Clone the repo to your machine
2. Open a command line to the root directory
3. `npm install`
4. `npm start`
5. Open IE 11
6. Hit F12
7. Browse to localhost:3000
8. Note the errors in the console

(Note, you must have node installed on your machine)

**Comment by mkay581** [comment]
Still running into this issue. @ljharb what is the correct polyfill to use? Looks like your link went stale.

**Comment by ljharb** [comment]
@mkay581 the link works for me - https://npm .com/object.assign works as well.

**Comment by JakeChampion** [comment]
@mkay581 What is the polyfill.io url you are using and what browsers do you see this issue in? The related patch for this was added on 6th March, I'm wondering if you are seeing another bug/issue.

**Comment by mkay581** [comment]
Actually we went with another solution. So I'm unable to recall the details of the issue now. Sorry!
