### ISSUE TITLE
NodeList iterator issue

### ISSUE THREAD

**Issue by daveykropf** [Financial-Times/polyfill-library#156]
[type]: A feature request?

## What
NodeList is not iterable in Edge <= 15.

For example the following code returns a `false` in older Edge browsers.
```js
Symbol.iterator in (document.querySelectorAll('.something'))
```

**Comment by JakeChampion** [comment]
All versions of Edge are served the [NodeList.prototype.@@iterator polyfill](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/NodeList/prototype/%40%40iterator/config.json#L3) and all versions of Edge pass our test suite.

If you are using https://polyfill.io you need to make sure that you include the polyfill in your features query parameter like so: https://polyfill.io/v3/polyfill.min.js?features=NodeList.prototype.%40%40iterator
