### ISSUE TITLE
requestIdleCallback and cancelIdleCallback missing

### ISSUE THREAD

**Issue by bmartel** [Financial-Times/polyfill-library#157]
## Feature request

Switched a larger project from using babel polyfill with many hand rolled polyfills to this service, which seems to work for the most part that I can see, other than one glaring omission of `requestIdleCallback` and `cancelIdleCallback`. I searched through the output of the v3 service, and around the repository but have been unable to find anything mentioning this.

Am I missing something somewhere, or is this just actually missing from the underlying polyfill service?

**Comment by Rendez** [comment]
I'd like to work on adding `rIC`, we also need it in the library. Is this something that might be in the scope of the core team? How can I get the ok-go?

**Comment by JakeChampion** [comment]
Hi @Rendez, apologies, I forgot to update this issue, @notlee is most of the way through creating and adding a requestIdleCallback polyfill. I will go through the issues now to mark which ones are in need of contributors :-)

**Comment by notlee** [comment]
👋 `requestIdleCallback` and `cancelIdleCallback` was released in [v3.34.0](https://github.com/Financial-Times/polyfill-library/releases/tag/v3.34.0) and has also been released to the polyfill service.

**Comment by Rendez** [comment]
@notlee amazing! thanks so much.
