### ISSUE TITLE
Missing ES2019 features like Object.fromEntries

### ISSUE THREAD

**Issue by esprehn** [Financial-Times/polyfill-library#159]
Feature Request

## What

Missing polyfills for ES2019:

Array#flat
Array#flatmap
Symbol#description
String#matchAll
Object.fromEntries

## Details

This is an empty file:
https://cdn.polyfill.io/v3/polyfill.min.js?features=es2019&flags=always

**Comment by JakeChampion** [comment]
Pr for this is https://github.com/Financial-Times/polyfill-library/pull/91

**Comment by JakeChampion** [comment]
These have all been added now :-)
