### ISSUE TITLE
Object.preventExtensions polyfill calls TypeError instead of Type

### ISSUE THREAD

**Issue by esprehn** [Financial-Times/polyfill-library#161]
Bug report

## What

Polyfill calls TypeError constructor instead of the Type() operation.

## Details

https://github.com/Financial-Times/polyfill-library/blob/1b3b661253ba375ca357d8d097a1586351cf439f/polyfills/Object/preventExtensions/polyfill.js#L6

**Comment by JakeChampion** [comment]
Fixed in https://github.com/Financial-Times/polyfill-library/commit/0a092404a35566807381bdd3311fc4ab51325b4c
