### ISSUE TITLE
Browserslist support

### ISSUE THREAD

**Issue by gbiorczyk** [Financial-Times/polyfill-library#162]
Hi,

I would like to write a code that allows me to automatically add all mixins for the browsers given in package.json.

Here's the part of the code in package.json:
```
"browserslist": [
  "last 3 versions"
],
```

I have something like this in the webpack file:
```
const browserslist = require('browserslist');
const list = browserslist();
console.log(list);
```

I get the following list of browsers:
```
[
'and_chr 71',
'and_ff 64',
'and_qq 1.2',
'and_uc 11.8',
'android 67',
'android 4.4.3-4.4.4',
'android 4.4',
'baidu 7.12',
'bb 10',
'bb 7',
'chrome 72',
'chrome 71',
'chrome 70',
'edge 18',
'edge 17',
'edge 16',
'firefox 65',
'firefox 64',
'firefox 63',
'ie 11',
'ie 10',
'ie 9',
'ie_mob 11',
'ie_mob 10',
'ios_saf 12.0-12.1',
'ios_saf 11.3-11.4',
'ios_saf 11.0-11.2',
'op_mini all',
'op_mob 46',
'op_mob 12.1',
'op_mob 12',
'opera 58',
'opera 57',
'opera 56',
'safari 12',
'safari 11.1',
'safari 11',
'samsung 8.2',
'samsung 7.2-7.4',
'samsung 6.2-6.4'
]
```

Here I found a list of all mixins and in each there is a file with a list of browsers for which it is required:
https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/CustomEvent/config.json

How can I check if the list of my browsers is in the scope of this from the config.js file?

**Comment by JakeChampion** [comment]
I would recommend using our npm package [create-polyfill-service-url](https://www.npmjs.com/package/create-polyfill-service-url) as it takes into account a browserslist file if one exists

**Comment by MrTimscampi** [comment]
> I would recommend using our npm package [create-polyfill-service-url](https://www.npmjs.com/package/create-polyfill-service-url) as it takes into account a browserslist file if one exists

Sorry to dig this backup, but what if we don't want to use an external service? There's some polyfills in this package that I'd like to add to https://github.com/jellyfin/jellyfin-web, but we don't rely on CDNs.

Is it possible to request a set of polyfills without specifying a user agent ?

**Comment by JakeChampion** [comment]
@MrTimscampi Yes but it is not advised because it results in larger bundles.

Here is how to do it:
```js
const polyfillLibrary = require('polyfill-library');

const featuresToPolyfill = ['es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018']; // etc etc

const includeWithFeatureDetection = new Set(['always', 'gated']);
const features = Object.fromEntries(featuresToPolyfill.map(feature => [feature, includeWithFeatureDetection]))

const polyfillBundle = polyfillLibrary.getPolyfillString({
	minify: true,
	features
}).then(function(bundleString) {
	console.log(bundleString);
});
```

**Comment by MrTimscampi** [comment]
Awesome, thank you :)
