### ISSUE TITLE
Object.getOwnPropertySymbols polyfill missing

### ISSUE THREAD

**Issue by niftylettuce** [Financial-Times/polyfill-library#166]

**Comment by JakeChampion** [comment]
The polyfill does exist, it exists as an [alias of the Symbol polyfill](https://github.com/Financial-Times/polyfill-library/blob/f7fe94f900c8fae9b97365a044b114514b0db732/polyfills/Symbol/config.json#L5) because they both need to be polyfilled at the same time.

**Comment by niftylettuce** [comment]
When you search for `Object.getOwnPropertySymbols` on the service it doesn't work though

**Comment by JakeChampion** [comment]
That's correct, we have an open issue on the polyfill-service repo for this --> https://github.com/Financial-Times/polyfill-service/issues/1944
