### ISSUE TITLE
Object.assign window.location in IE11 Bug

### ISSUE THREAD

**Issue by taddei** [Financial-Times/polyfill-library#17]
It looks like in IE11, trying to do the following results in an error.

```javascript
Object.assign({}, window.location)
```
This pattern is currently used by https://github.com/reach/router for example, breaking our pages in IE11

I've created a JSBin to highlight the issue

https://jsbin.com/yigocowero/1/edit?html,console

**Comment by JakeChampion** [comment]
This was fixed in https://github.com/Financial-Times/polyfill-library/pull/155 and published in https://github.com/Financial-Times/polyfill-library/releases/tag/v3.32.0
