### ISSUE TITLE
Pass user agent to library

### ISSUE THREAD

**Issue by underbyte** [Financial-Times/polyfill-library#176]
## Details
CDN provider such as fastly provide a UA parsing at the edge layer orI would like to manually parse the UA myself and pass it to `getPolyfillString `. Would it be possible to skip the UA parsing [here](https://github.com/Financial-Times/polyfill-library/blob/master/lib/index.js#L104) done at the edge layer?

**Comment by JakeChampion** [comment]
We will use the value of `opts.ua` without modification if it matches the format `/^(\w+)\/(\d+)(?:\.(\d+)(?:\.(\d+))?)?$/i` -- https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/lib/normalise-user-agent.js#L16
