### ISSUE TITLE
Add polyfill for Object.createEntries

### ISSUE THREAD

**Issue by lesleh** [Financial-Times/polyfill-library#186]
Add polyfill for `Object.createEntries()`

## What
[Object.createEntries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries) is now a Stage 4 tc39 proposal, and has been implemented in Chrome 73 and Firefox 63.

## Details

There is a [working polyfill on the proposal Github](https://github.com/tc39/proposal-object-from-entries/blob/master/polyfill.js) so all that would need to be done is define the browsers supported and to write some tests for it.

**Comment by JakeChampion** [comment]
A pull-request for this already exists --> https://github.com/Financial-Times/polyfill-library/pull/91
