### ISSUE TITLE
Element.prototype.scroll

### ISSUE THREAD

**Issue by nicksrandall** [Financial-Times/polyfill-library#190]
This is a feature request to add "Element.prototype.scroll", "Element.prototype.scrollBy" and "Element.prototype.scrollIntoView" to the library.

## What
This feature is a bit hard to detect because most older browsers support the method but they do not support the extended function signature and the "smooth scrolling" effect.

## Details
- I'd like to use the `"mode": "smooth"` option when using these methods on an element.

## Additional information
- An accurate polyfill that I've used in the past can be found here: https://github.com/iamdustan/smoothscroll
- I'd be happy to open up a PR for this... my largest question is if this should be 3 separate polyfills or if it should be bundled all-in-one. The latter approach seems to make the most sense to me.

**Comment by JakeChampion** [comment]
This was added in https://github.com/Financial-Times/polyfill-library/pull/313
