### ISSUE TITLE
window.crypto polyfill missing

### ISSUE THREAD

**Issue by niftylettuce** [Financial-Times/polyfill-library#195]
https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto
https://github.com/vibornoff/webcrypto-shim

`window.crypto() is not supported in IE 10`

**Comment by jamesarosen** [comment]
IE11 has a Crypto module, but it's namespaced as `msCrypto` and not spec-compliant. See https://github.com/vibornoff/webcrypto-shim

**Comment by RiZKiT** [comment]
Stumbled upon this today https://github.com/firebase/firebase-js-sdk/blob/631a0ec5982b36382a96c15be9916bf29f98a01f/packages/firestore/src/platform_browser/browser_platform.ts#L81-L93 maybe it helps.

**Comment by JakeChampion** [comment]
Closing this issue as we do not have the capacity to implement this polyfill.
If anyone wants to contribute this polyfill please feel free to open a pull-request :-)
