### ISSUE TITLE
Exception with Map polyfill

### ISSUE THREAD

**Issue by sergeymorkovkin** [Financial-Times/polyfill-library#196]
Here is what's causing this error: [_ESAbstract/Type](https://github.com/Financial-Times/polyfill-library/blob/2082d51a9385f217484cb3a2302d2ecacb468372/polyfills/_ESAbstract/Type/polyfill.js#L18).

It's breaking things in IE 10/11 for the Map polyfill.

**Comment by JakeChampion** [comment]
Hi @sergeymorkovkin Please let me know:
- The browser you see the exception in
- The full polyfill.io url you are using
- A small amount of code which reproduces the exception (you can post it on https://jsbin.com/ or similar)

Without that information I will really struggle to help resolve this issue.

**Comment by sergeymorkovkin** [comment]
1. IE version 10.0.9200.17492
2. Using custom-built bundle

      'CustomEvent',
      'IntersectionObserver',
      'IntersectionObserverEntry',
      'Element.prototype.classList',
      'Element.prototype.closest',
      'HTMLPictureElement',
      'fetch',
      'NodeList.prototype.forEach',
      'Array.prototype.forEach',
      'Element.prototype.dataset',
      'Map',
      'Set',
3. These sites don't seem to support IE10. So, try with the following:

> <script src="https://polyfill.io/v3/polyfill.min.js?features=Map"></script>
> <script>var m = new Map(); m.set({}, {});</script>

**Comment by jkerr321** [comment]
Hi @sergeymorkovkin,

I've tested the script provided in IE10 - 
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=Map"></script> <script>var m = new Map(); m.set({}, {});</script>
```
as well as a version of the script including all the polyfills you've listed.

Both cases worked fine, and no errors were thrown in either case, so I am going to close this issue for now.

FYI, if you'd like to reproduce my test you can do so by visiting the following URLs in IE10:
* For the simple script - https://output.jsbin.com/hicesaxiha
* For the script with multiple polyfills - https://output.jsbin.com/fejigabuva/1
