### ISSUE TITLE
[question] Is there any change to split this library into polyfill-library and polyfill-list

### ISSUE THREAD

**Issue by sleagon** [Financial-Times/polyfill-library#199]
We have been using this library since last year, when this library was still a part of polyfill-service. We believe the most valuable thing this library provides is the polyfills, not the getter. We need to custom the UA parser to avoid some edge cases we run into. Based on the pure polyfill list, anyone can write their getter as they need. Of cause standard is necessary, anyone can provide polyfills according your standard.

This is just a simple advice, thanks for your guys nice work.

**Comment by chee** [comment]
Hello, @sleagon, thanks for your contribution. This isn't on the roadmap right now, I'm afraid.

Would you be in a position to share the edge cases that you run into so that we can fix them in the main library and improve the service for all users?

**Comment by sleagon** [comment]
We are using this library in production env, the user-agent parser used here is too aggressive, which want to cover as much browsers as possible. We use a relative conservative parser which can cover most famous browser like chrome/edge/firefox/safari and ignore other browsers.  We think reliability is more important than extremely performance, after all, the User-Agent is too unreliable.

**Comment by sleagon** [comment]
In China, there is so many customed browsers and webviews, we can't take risk to cover all of them.
