### ISSUE TITLE
RegExp.prototype.flags should be polyfilled for all Edge versions

### ISSUE THREAD

**Issue by levenleven** [Financial-Times/polyfill-library#206]
## What
`RegExp.prototype.flags` is not available in all Edge versions, but in configuration polyfill requested only for `"edge": "<13"`

## Details
- Browser - Edge 18
- Device - Desktop

**Comment by JakeChampion** [comment]
This has now been fixed via https://github.com/Financial-Times/polyfill-library/pull/482
