### ISSUE TITLE
Feature Request: add polyfill for TextEncoder and TextDecoder

### ISSUE THREAD

**Issue by lpd-au** [Financial-Times/polyfill-library#207]
## What
Add a polyfill for [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) and [TextDecoder](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder) capable of encoding and decoding UTF-8.

## Details
IE11 and EdgeHTML do not have support for the `TextEncoder.prototype.encode` and `TextDecoder.prototype.decode` apis. Native implementations of TextEncoder must only encode to UTF-8 but TextDecoder may support other encodings, however it is imo rare to use any other in practice given it's not reversible, so it would be sufficient to throw a RangeError when constructing a TextDecoder for any other encoding.

My use case for this polyfill is in combination with websockets. Websockets support a text and binary mode, and I would like to use this api to decode strings transmitted within the binary data (when `aWebSocket.binaryType` is set to `arraybuffer`), as well as send encoded strings back to the server.

## Additional Information

MDN has a [working polyfill for TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#Polyfill) but not for TextDecoder. I submitted a request to that repo but was directed here instead: https://github.com/mdn/sprints/issues/1508.

**Comment by JakeChampion** [comment]
This was added in [`#672`](https://github.com/Financial-Times/polyfill-library/pull/672) and released in [`v3.96.0`](https://github.com/Financial-Times/polyfill-library/releases/tag/v3.96.0)
