### ISSUE TITLE
Feature Request: inert polyfill

### ISSUE THREAD

**Issue by andrewgadziksonos** [Financial-Times/polyfill-library#210]
## What

Would like to add the [Element.prototype.inert](https://html.spec.whatwg.org/multipage/interaction.html#inert) polyfill

## Details

`Element.prototype.inert` is a new spec that landed over a year ago and is currently still in progress.  It's hidden behind a flag in Canary Chrome currently, and no other browser supports it natively.  Would be nice to manage the polyfill in this service and as browsers start to implement it natively in the future we can just update the browser list.

PR submitted -  https://github.com/Financial-Times/polyfill-library/pull/197

**Comment by JakeChampion** [comment]
PR for this is -> #197

**Comment by JakeChampion** [comment]
fixed via https://github.com/Financial-Times/polyfill-library/pull/197
