### ISSUE TITLE
Feature Request: ResizeObserver polyfill

### ISSUE THREAD

**Issue by andrewgadziksonos** [Financial-Times/polyfill-library#211]
## What
Would like to add the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) polyfill

## Details

The `ResizeObserver` interface reports changes to the content rectangle of an Element or the bounding box of an SVGElement. The content rectangle is the box in which content can be placed, meaning the border box minus the padding. 

Support is rapidly gaining momentum, so it would be nice to manage this polyfill in this service.  
https://caniuse.com/#feat=resizeobserver

PR submitted https://github.com/Financial-Times/polyfill-library/pull/212

**Comment by aronwoost** [comment]
Can be closed, because PR was merged. 👍

**Comment by nicooprat** [comment]
Looks like the repo is abandoned, and I had a lot of issues with this polyfill especially on Safari 13 and IE 11. This one looks more robust and updated: https://github.com/juggle/resize-observer/ Would you mind use this one instead? 🙏

**Comment by JakeChampion** [comment]
Sure thing @nicooprat, are you able to contribute that change to the project?

**Comment by nicooprat** [comment]
@JakeChampion Here's my first try ;) https://github.com/Financial-Times/polyfill-library/pull/644
