### ISSUE TITLE
Map polyfill-library modules to core-js modules to make babel core-js exclusion easy.

### ISSUE THREAD

**Issue by neenhouse** [Financial-Times/polyfill-library#216]
Applications that are leveraging run-time polyfills provided through a service need to configure their clients to remove polyfills from their bundles so they can be supplied by a service.  We are internally hosting a service that leverages polyfill-library to provide those polyfills and now are working on a standardized plugin that can:

- Define babel exclusions for coreJS 3 modules that can be satisfied by polyfill-library
- Automatically generate URL based on desired feature leverage from polyfill-library

We are moving ahead with our implementation but want to surface our mapping proposal to broaden the conversation to the community here.

This is still a WIP and a proposal PR will be coming.

**Comment by JakeChampion** [comment]
This sounds great, if you are thinking of making your projects open-source, then I would be eager to lend a hand :-)
