### ISSUE TITLE
IE11 Object.getOwnPropertyNames: argument is not an object issue

### ISSUE THREAD

**Issue by rubtsovi** [Financial-Times/polyfill-library#218]
[type]: A bug report
## What
A Symbol polyfill which is dependency for some others polyfills occurs error in IE11 `Object.getOwnPropertyNames: argument is not an object`. 

## Details
When I try this combination of polyfills `https://polyfill.io/v3/polyfill.js?flags=gated&features=fetch%2CArray.from%2CWeakSet` on clean project there's no issues. So probably it occurs because of one of other packages pass not correct value, I logged it and it's `0` value.

## Solution
I think, better to add `try-catch` block for `gOPN` function in Symbol polyfill:
```
try{
	return nGOPN(obj);
} catch (e) {
	return [];
}
```
If you think that's OK, I could make PR.

**Comment by slorber** [comment]
Hi,

I have the same problem with polyfill.io and react-dates. Did you find any workaround?

Jordan Harband suggests here that the polyfills provided by the service may be broken or not spec complient: https://github.com/airbnb/react-dates/issues/1625#issuecomment-546404462

**Comment by agriffis** [comment]
I'm running into this too. What do we need to get this fixed?

**Comment by agriffis** [comment]
@JakeChampion Thank you!!

Two quick questions:

1. When do you anticipate this will be deployed to the service?

2. I'm still getting the old responses from polyfill.io (before the Object.keys fix) depending on the query string. How long before the CDN invalidates those?

**Comment by agriffis** [comment]
I'm still tripping on this and I tracked it down to the gated flag.

Here are examples:

* https://misc.arongriffis.com/polygood.html uses https://polyfill.io/v3/polyfill.js?features=Object.getOwnPropertyNames,Symbol
* https://misc.arongriffis.com/polybork.html uses https://polyfill.io/v3/polyfill.js?features=Object.getOwnPropertyNames,Symbol|gated

Open up the console on IE11 and you'll see the first one succeeds, the second one doesn't.

The only difference between them is the second one changes `Symbol` to `Symbol|Gated`

**Comment by JakeChampion** [comment]
fixed in [v3.52.2](https://github.com/Financial-Times/polyfill-library/releases/tag/v3.52.2) and now live on polyfill.io

**Comment by JakeChampion** [comment]
Thank you for such a good reproducible example @agriffis 👍

**Comment by agriffis** [comment]
Ah, forgot to II the IIFE!  Good find!

**Comment by JakeChampion** [comment]
I plan to write a test for this type of bug (where the detect expression is always truthy by accident) :-)
