### ISSUE TITLE
`Map` polyfill (`get(key)`) is very slow 

### ISSUE THREAD

**Issue by craigkovatch** [Financial-Times/polyfill-library#219]
We recently starting using `polyfill-library@3.34.0` to polyfill ES6 for (only) IE11 in Tableau. This caused a severe performance regression in our rendering code, which was traced to the `Map` polyfill. Removing `Map` and `Set` from our config resolved the issue -- luckily our code only currently needs the native partial support for `Map` in IE11. (I don't know if removing `Set` was also necessary, but since IE11 has partial support for both, I decided to err on the side of removing both.)

Unfortunately I have not investigated deeply enough to suggest a fix, but our profiling session indicated `CreateMethodProperty(Map.prototype...) (23.1.3.6 Map.prototype.get (key))` was the culprit.

Here is our config, for reference:
```
const ie11_es6_opts = {
  uaString: 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko',
  minify: false,
  excludes: [
    'Map',
    'Set',
  ],
  features: {
    'es6': { flags: ['gated'] }
  }
};
```

**Comment by neenhouse** [comment]
Observed same perf issue with Map.  `SameValueZero` is executed millions of times in comparison to `get` and `set` being executed 10s of thousands of times.

**Comment by neenhouse** [comment]
I suspect the root of the perf issue is mainly the internal algo's `Map` uses are O(n) computations, and when you are performing another O(n) operation on a Map structure the perf cost hit becomes O(n^2) and you get exponential slow down.  See https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Map/polyfill.js#L272 for examples.

Solution could be to make the iteration computation O(1) for Map's internals using some kind of hash table or maybe even converting the internal `_keys` property to an object (instead of an array).   I could get the ball rolling on this idea.  This issue is definitely hindering us from fully leveraging these polyfills.

**Comment by JakeChampion** [comment]
@neenhouse If that optimisation can be made whilst adhering to the specification steps, we will gladly accept the contribution. Thank you for offering to work on this :-)

**Comment by zloirock** [comment]
> If that optimisation can be made whilst adhering to the specification steps

Specification steps are not something that should be interpreted as an algorithm for implementation. [See the spec](https://tc39.es/ecma262/#sec-map-objects):

> Map object must be implemented using either hash tables or other mechanisms that, on average, provide access times that are sublinear on the number of elements in the collection. The data structures used in this Map objects specification is only intended to describe the required observable semantics of Map objects. It is not intended to be a viable implementation model.

**Comment by JakeChampion** [comment]
@zloirock Good point! I missed that part when reading the spec, thanks for pointing it out.

@neenhouse, feel free to implement a more optimised implementation :-)

**Comment by craigkovatch** [comment]
FWIW `Set` has the same issue -- should it be tracked separately or included in here?

**Comment by craigkovatch** [comment]
Any update on this? We would really like to be able to use Set/Map

**Comment by JakeChampion** [comment]
PR for this here --> https://github.com/Financial-Times/polyfill-library/compare/%23219

**Comment by JakeChampion** [comment]
fixeas in #293

**Comment by craigkovatch** [comment]
@JakeChampion do I need to open a new issue for also fixing `Set`?

**Comment by JakeChampion** [comment]
@craigkovatch Yes please, if you could link it to this issue that would be great
