### ISSUE TITLE
Bug: Map detection fails in strict mode

### ISSUE THREAD

**Issue by Ruud-Zuiderlicht** [Financial-Times/polyfill-library#225]
## What
I noticed Map is being polyfilled even though I have it gated. The browser is Chrome 75 (latest release at the moment). I did bypass the browser detection by downloading the actual code using IE. This was needed to make sure 3rd parties have the polyfills.

It turns out the browser runs into a feature-detect check that errors out. The check in question is `function () { ... 'Symbol' in this ... }`. Where this is `undefined`. This makes the code execute the catch clause. (See https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Map/detect.js)

## Details
The expected behavior is that Map isn't polyfilled, because the detection script skips this part of the code.

The actual behavior is that Map is being polyfilled.

To reproduce,
1. Include the generated code from polyfill.io using these settings: https://polyfill.io/v3/polyfill.js?flags=gated&features=Map (Chrome will generate no code, I had to download using IE to include the code)
2. Open the page containing step 1. there will be no error because of a try .. catch
3. Place a break point at this line https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Map/detect.js#L6
4. Inspect `this`; it wil be undefined

Browser: Google Chrome is up to date, Version 75.0.3770.100
Device: Desktop
![image](https://user-images.githubusercontent.com/18439859/59908480-d0cb9780-940d-11e9-9cf3-f7a26950098d.png)

_edit: I've updated the title as this issue isn't related to a bug in Chrome, but the usage of strict mode outside of the polyfill code._

**Comment by JakeChampion** [comment]
Hi there @Ruud-Zuiderlicht.

Which version of IE did you use to generate the bundle? When I use IE/11 and run the polyfill bundle in Chrome, it works correctly.

URL I used: https://polyfill.io/v3/polyfill.js?flags=gated&features=Map&ua=ie/11
Here is a JSBin which shows it working as expected: https://jsbin.com/codetezuye/edit?html,console

**Comment by Ruud-Zuiderlicht** [comment]
I tried the JSBin and didn't get the error either, but I forgot to mention that I placed the code inside a file that is compiled by Webpack. I tried moving the polyfill outside of that file and then everything works as expected. So I expect Webpack to declare strict mode, which explains the behavior. I've moved the code outside of Webpack to fix for now.

Is there a way to improve on this on your side as well?

**Comment by JakeChampion** [comment]
Let's see if making the entire bundle be in strict mode can work --> https://github.com/Financial-Times/polyfill-library/pull/226

If it doesn't work, I guess we would have to close this issue as we likely can not make the entire bundle in strict mode
