### ISSUE TITLE
Bug: Intl.PluralRules are not available on Safari

### ISSUE THREAD

**Issue by xeophin** [Financial-Times/polyfill-library#227]
## What
While Safari supports some of the `Intl` constructors (e.g. `DateTimeFormat` or `NumberFormat`), it has currently no support for `PluralRules`. (See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules)). Would it be possible to extend the delivery of the `Intl` polyfill to newer versions of Safari as well?

## Details

**Current:** polyfill.io will deliver no `Intl` polyfill to Safari > 10.

**Expected:** polyfill.io keeps on delivering the `Intl` polyfill to Safari < 13 (`PluralRules` is available in the current Safari Technology Preview).

## Why
[intl-messageformat](https://www.npmjs.com/package/intl-messageformat) requires `Intl.PluralRules` to be available from v3.0.0 on.

**Comment by longlho** [comment]
@JakeChampion  I'd love to contribute a fix to this and some more `Intl.*` APIs but wasn't sure if ES3 support is required? Most `Intl` libs require IE11 at least since that has `Intl.DateTimeFormat` & `Intl.NumberFormat` which are important building blocks.

**Comment by JakeChampion** [comment]
Fixed via #301
