### ISSUE TITLE
Core polyfill bug (unable to get property of undefined or null reference)

### ISSUE THREAD

**Issue by niftylettuce** [Financial-Times/polyfill-library#229]
When using IE10 with this URL, the following error occurs:

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6,Map,Map.prototype,Math.sign,Promise,Reflect,Symbol,Symbol.iterator,Symbol.prototype,Symbol.toPrimitive,Symbol.toStringTag,Uint32Array,window.crypto"></script>
```

https://polyfill.io/v3/polyfill.min.js?features=es6,Map,Map.prototype,Math.sign,Promise,Reflect,Symbol,Symbol.iterator,Symbol.prototype,Symbol.toPrimitive,Symbol.toStringTag,Uint32Array,window.crypto&ua=ie/10

<img width="1270" alt="Screen Shot 2019-06-10 at 5 33 35 PM" src="https://user-images.githubusercontent.com/523141/59232976-35842800-8bac-11e9-8a48-3ec8a15184b8.png">

Possibly related to https://github.com/Financial-Times/polyfill-service/issues/145

**Comment by niftylettuce** [comment]
Related to #218, also happens in IE11.

**Comment by JakeChampion** [comment]
This looks to be fixed, I tested the polyfill.io script tag on ie 10 and no errors were thrown

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1569131/97290913-1d648580-1841-11eb-9fef-e9444b2a49d3.png">
