### ISSUE TITLE
Cut new release and publish to NPM

### ISSUE THREAD

**Issue by nicksrandall** [Financial-Times/polyfill-library#256]
# Chore: Publish the latest version of lib to NPM

## What
I'm not sure where is the best place to request this but I'd like to get a new version of this library on NPM. I'm specifically looking for a version with the recently added `HTMLTemplateElement` polyfill. Is there any kind of release cadence with this library?

It would also be nice if we could get this more recent version of lib deployed to public polyfill service. I'm happy to contribute where I can.

Thanks for your help and for this awesome library!

**Comment by JakeChampion** [comment]
Version 3.35.0 has been published :-) 
https://github.com/Financial-Times/polyfill-library/releases/tag/v3.35.0
