### ISSUE TITLE
Polyfill for HTMLSelectElement.selectedOptions

### ISSUE THREAD

**Issue by garygreen** [Financial-Times/polyfill-library#257]
Would it be worthwhile adding a polyfill for this? Seems to be supported in all browsers except IE. Polyfill looks [pretty small](https://github.com/shvaikalesh/shim-selected-options/blob/master/index.js)

![image](https://user-images.githubusercontent.com/1702638/60984609-e6105380-a333-11e9-8f02-154ffd6eeeab.png)

Ref: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions

**Comment by JakeChampion** [comment]
Hey @garygreen, yes I think this polyfill would be useful to have in the service. Would you like to have a go at contributing the polyfill as a pull-request? If not, I will add a label to this issue asking for contributors :-)

**Comment by GreatWizard** [comment]
Hey, my coworkers and I have an issue with selectedOptions not available on IE11.
We just found a polyfill by @brettz9 that do the job: https://gist.github.com/brettz9/4212217#file-htmlselectelement-prototype-selectedoptions-js-L259
