### ISSUE TITLE
[feature-request] `Object.fromEntries`

### ISSUE THREAD

**Issue by jhpratt** [Financial-Times/polyfill-library#259]
## What

A polyfill for this [proposal], which has reached stage 4.

## Details
See _Rationale_ and _Motivating examples_ in the [proposal].

This is already implemented in `corejs`. Lodash has a `fromPairs` method, but this is only for simple array pairs, not more complex examples like creating an object from a `Map`.

[proposal]: https://github.com/tc39/proposal-object-from-entries

**Comment by JakeChampion** [comment]
This was added in https://github.com/Financial-Times/polyfill-library/releases/tag/v3.35.0
