### ISSUE TITLE
Support For Multiple Paths

### ISSUE THREAD

**Issue by urstrulyKarthik** [Financial-Times/polyfill-library#26]
Feature Request

## What

Firstly, this is a great library with a very large list of maintained polyfills. Kudos to the authors / maintainers. While looking into the way the polyfills are resolved in run time depending on the browser, I felt this is a much cleaner way of maintaining things. Even if we are to write our own polyfill library that achieves the same functionality, much of this source code from the 'lib' directory (UA class, alias resolver etc) could be re used. However, currently this module has the polyfill directory path hardcoded in the sources.js which restricts it to consider only the dist folder of this library. I would like to check if there's a plan to extend this to an array of paths which could be specified through options. The paths could be a 'dist' folder of another npm module(s) which follow the same structure and format to author and build polyfills like this module does.
## Details
`const polyfillDirectory = path.join(__dirname, "../polyfills/__dist");`
Can this be enhanced to
`const polyfillDirectory = [path.join(__dirname, "../polyfills/__dist");]` or
`const polyfillDirectory = [...options.paths]`

**Comment by JakeChampion** [comment]
Hi @urstrulyKarthik, we used to have this functionality and removed it because it was not being used anywhere and complicated the codebase somewhat. We found that the polyfills that are in the project solve the issues of most (if not all) of our users' issues.

May I ask why you are wanting to implement/bring-your-own polyfills rather than contribute them to the polyfill-library? I'd like to know if there is a way to cater to your needs without having this feature. If there isn't then we can most likely re-add the feature.

**Comment by urstrulyKarthik** [comment]
We are working on a framework / platform which would be used by customers with certain customization. As a part of the customization, they can have their own packages (with polyfills written). We could contribute to the polyfill library but it could be a pain to ask the customers to contribute to the polyfill library. Hence wanted to check if this feature could be re-added. Thanks in advance.

**Comment by JakeChampion** [comment]
We won't be re-adding this feature as it would make the current polyfill folder structure and config.json format become part of the public api, which we are wanting to avoid because we are thinking of refactoring how the polyfill-library works internally.

**Comment by aselhid** [comment]
Hi, i have similar problem to this one. Is there any solution for this particular case? Thanks in advance!
