### ISSUE TITLE
Object.getOwnPropertyDescriptors missing

### ISSUE THREAD

**Issue by cyjake** [Financial-Times/polyfill-library#261]
A bug report.

## What

It seems [`Object.getOwnPropertyDescriptors`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors#Specifications) is missing neither in the es2017 feature bundle nor as a single polyfill. According to MDN this function is standard in es2017. 

## Details

- Visit <https://polyfill.io/v3/polyfill.min.js?features=es2017> in Chrome 50 
- The response polyfill bundle should contain polyfill for `Object.getOwnPropertyDescriptors`

**Comment by JakeChampion** [comment]
Yep, this polyfill is currently missing.

It can definitely be added:
Here is the spec for the feature --> https://tc39.es/ecma262/#sec-object.getownpropertydescriptors
Here are the browsers which would require the polyfill:
edge: <15
chrome: <54
firefox: <50
safari: <10

**Comment by cyjake** [comment]
should I send a pr?

**Comment by JakeChampion** [comment]
@cyjake that would be great!
