### ISSUE TITLE
Android stock 4.4.2 and CustomEvent

### ISSUE THREAD

**Issue by mustafa0x** [Financial-Times/polyfill-library#286]
The following user agent does not seem to support CustomEvent, but polyfill.io isn't serving it to them.

`Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SM-G350E Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

**Comment by JakeChampion** [comment]
Hi @mustafa0x, can you please post the full polyfill.io url you are using, that would help in debugging this a lot.

The useragent you posted is for android 4.4, which will not be served the CustomEvent polyfill as we only serve it to android 4.3 or lower. -- https://github.com/Financial-Times/polyfill-library/blob/b989891f8e161997e48a3d42b8ab28656a84063d/polyfills/CustomEvent/config.toml#L22

**Comment by mustafa0x** [comment]
https://polyfill.io/v3/polyfill.min.js?features=default,fetch,Object.entries,Array.prototype.includes

My JS error logs contain `Uncaught ReferenceError: CustomEvent is not defined` for the following UserAgents.

```
Mozilla/5.0 (Linux; U; Android 4.4.4; en-us; SM-G357FZ Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.4; ar-ae; GT-I9060I Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; ar-ae; SCH-I605 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; fa-ir; SM-T211 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; fr-fr; GT-N7100 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24
```

I'm not sure how to verify whether those UAs actually have CustomEvent or not.
