### ISSUE TITLE
Don't serve Array.prototype.flat/flatMap to newer browsers

### ISSUE THREAD

**Issue by AdriVanHoudt** [Financial-Times/polyfill-library#287]
Update request

## What

Currently Array.prototype.flat is served to newer browsers while not required anymore.
See https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Array/prototype/flat/config.toml
## Details

Current support can be checked with Kangax http://kangax.github.io/compat-table/es2016plus/#test-Array.prototype.{flat,_flatMap}_Array.prototype.flat_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;
and canIuse https://caniuse.com/#feat=array-flat

If you want I can try and do a PR for this

**Comment by AdriVanHoudt** [comment]
Awesome, thanks!
Do you have an ETA for when this will go live?

**Comment by JakeChampion** [comment]
It was just released as v3.38.0 -- https://github.com/Financial-Times/polyfill-library/releases/tag/v3.38.0
It should go live on polyfill.io sometime tomorrow :-)

**Comment by AdriVanHoudt** [comment]
That's quick 👌

**Comment by JakeChampion** [comment]
It's live now :-)
