### ISSUE TITLE
Polyfill error on Mobile Safari UI/WKWebView Can't find variable: IntersectionObserver

### ISSUE THREAD

**Issue by SaraBCL** [Financial-Times/polyfill-library#288]
Bug Report

## What

The IntersectionObserver polyfill was working perfectly until we added the gated flag parameter and started to get logs with the error : 
`Can't find variable: IntersectionObserver`

## Details
The error occurs under these circumstances : 

- browser versions : Mobile Safari UI/WKWebView 12.1.X (0 < X < 4)
- devices : several versions of IPhones and IPads. (Iphone 6, 8, SE...)
- OSes: IOS 12.1.X
- Example user-agent : 

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57 Instagram 103.0.0.12.116 (iPhone8,4; iOS 12_1_4; ...)`

## Additional information
I realize WKWebView is not explicily in the list of supported browsers, but the polyfill already works for it since we never had this issue before we released the gated param addition, I suspect it's only an issue with the gate for Intersection observer.

Thank you for your time, hope we can find a solution !

**Comment by JakeChampion** [comment]
Hi @SaraBCL, could you please post the full polyfill.io URL you are using, that would help me in figuring out exactly what is going on here :-)

**Comment by SaraBCL** [comment]
Hi, thanks for checking in so soon, here it is !
`https://polyfill.io/v3/polyfill.min.js?flags=gated&features=IntersectionObserver,Intl.~locale.en,Intl.~locale.en-GB,Intl.~locale.en-CA,Intl.~locale.fr-BE,Intl.~locale.fr-FR,Intl.~locale.nl-BE,Intl.~locale.nl-NL,Intl.~locale.de-DE,Intl.~locale.da-DK,Intl.~locale.nb-NO,Intl.~locale.es-ES,Intl.~locale.es-CL`

**Comment by JakeChampion** [comment]
Thanks!

I can see that the useragent gets parsed into `ios_saf/12.1.0`, and we were not serving IntersectionObserver to that particular browser. We have just fixed that issue in #284.

Your issue will be fixed in the next release of the polyfill-library and polyfill-service :-)

**Comment by SaraBCL** [comment]
Perfect, thank you !

**Comment by JakeChampion** [comment]
It's live now on https://polyfill.io :-)
