### ISSUE TITLE
[feature-request] Add EventTarget polyfill

### ISSUE THREAD

**Issue by Vanilagy** [Financial-Times/polyfill-library#291]
I think it would be awesome if you guys added a polyfill for EventTarget, as it is not available in Safari, yet is a vital component of any complex application I make.

Current workarounds include substituting EventTarget for Element, or including some polyfill, in which case I usually go for: https://github.com/ungap/event-target

**Comment by JakeChampion** [comment]
duplicate of https://github.com/Financial-Times/polyfill-library/issues/252
