### ISSUE TITLE
How do you run the test suite locally?

### ISSUE THREAD

**Issue by KaptajnKold** [Financial-Times/polyfill-library#292]
In order to contribute to this project, I would assume that it is required to be able to run the test suite. To be able to do so, it looks like some credentials for BrowserStack are required. What is one to do, if one does not have a BrowserStack account? On the BrowserStack website, I can see that BrowserStack is free for open source projects. Does this mean there are some credentials would-be contributors can use?

In any case, it would be very helpful if the README or contributing guidelines included some documentation about how to run the test suite locally.

**Comment by neenhouse** [comment]
You can look at `package.json` and see the NPM `scripts` targets to see what commands are available.  

```
npm run test-polyfills -- --features=default
```

☝️ that starts a Karma server at `http://localhost:9876` and then you can navigate to it with the target platform you want to test.  No browser stack required and you get fast feedback loop for debugging.

**Comment by JakeChampion** [comment]
You can also run the test suite by submitting a pull-request and our CircleCI setup will run the tests for you
