### ISSUE TITLE
URL polyfill fails in IE if used with strict mode bundling process

### ISSUE THREAD

**Issue by niksy** [Financial-Times/polyfill-library#297]
## What

When trying to use `URL` polyfill with bundling JS with bundler like Webpack or Rollup, polyfilling fails in IE11 if module is in strict mode (using it with ES `import` makes code behave in strict mode). This is related to [already closed issue](https://github.com/Financial-Times/polyfill-library/issues/225), but now error happens in different part of codebase, pinpointed [here](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/_ESAbstract/Type/polyfill.js#L18).

It seems like referencing `this` makes it `undefined` in strict mode. Should this be changed to something like `self`? Also, if this is welcome change, maybe this should be reflected to every part of codebase where `this.Symbol` is defined.

## Details

Polyfills are expected to work in strict mode when `this` is used to reference globally defined properties such as `Symbol`.

**Comment by JakeChampion** [comment]
Thanks for the issue, I agree with changing `this` to `self`, will you be making a pull-request with the change? If not, I will happily make the change myself :-)

**Comment by niksy** [comment]
I will make PR!

**Comment by niksy** [comment]
@JakeChampion done!
