### ISSUE TITLE
Intl.PluralRules is not supported by polyfill.io on IE11

### ISSUE THREAD

**Issue by jgabriele** [Financial-Times/polyfill-library#299]
## What
When fetching (in both v2 and v3) the **Intl** polyfill from IE11, it returns an empty file:

> https://polyfill.io/v3/polyfill.min.js?features=Intl

## Details
According to [this caniuse report](https://caniuse.com/#feat=internationalization), this makes sense. But [Intl.PluralRules support](https://caniuse.com/#feat=intl-pluralrules&search=Intl) is not supported by IE11 and would need a polyfill.

Expected behaviour would be either to be able to request `Intl.PluralRules` directly

> https://polyfill.io/v3/polyfill.min.js?features=Intl

Or get **only** the PluralRules part when requesting `Intl` on IE11.

**Comment by TheDadi** [comment]
Open PR that fixes this! 🥇 
https://github.com/Financial-Times/polyfill-library/pull/301

**Comment by JakeChampion** [comment]
fixed via https://github.com/Financial-Times/polyfill-library/pull/301
