### ISSUE TITLE
[feature request] window.queueMicrotask

### ISSUE THREAD

**Issue by kapouer** [Financial-Times/polyfill-library#303]
https://github.com/feross/queue-microtask

Thanks !

**Comment by JakeChampion** [comment]
Yes this would be a good polyfill to add! Whoever wants to contribute this polyfill, please comment on this issue :-)

We can create our own polyfill for this which depends upon our Promise polyfill.

Browser support:
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/queueMicrotask#Browser_compatibility

We would create a new folder inside `./polyfills` named `queueMicrotask` and create 4 files within this folder:
`polyfill.js` -- The polyfill code itself
`detect.js` -- An expression which detects if queueMicrotask exists in the user-agent ( `"queueMicrotask" in this` would be a good expression to use)
`config.toml` -- The configuration which states any dependencies the polyfill has on other features/polyfills and what user-agents/browsers need the polyfill
`tests.js` -- A test suite to prove the polyfill works correctly

The specification for the feature is here -- https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#microtask-queuing

Some tests already exist for this feature within the web-platform-tests projects, we should/could base our tests off of those ones. (https://github.com/web-platform-tests/wpt/blob/master/html/webappapis/microtask-queuing/queue-microtask-exceptions.any.js and https://github.com/web-platform-tests/wpt/blob/master/html/webappapis/microtask-queuing/queue-microtask.any.js)

A good folder in this project to look at if unsure about what to do would be `requestIdleCallback` https://github.com/Financial-Times/polyfill-library/tree/master/polyfills/requestIdleCallback which @notlee contributed.

If you have any questions about what to do, please feel free to contact me :-)

**Comment by JakeChampion** [comment]
Added in #461
