### ISSUE TITLE
classList polyfill missing .replace() function

### ISSUE THREAD

**Issue by lenovouser** [Financial-Times/polyfill-library#304]
- [developer.mozilla.org/docs/web/api/element/classlist](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) (they have a polyfill that seems to include `.replace()` too there)

 - [developer.mozilla.org/docs/web/api/domtokenlist/replace](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace) `DOMTokenList.replace()`

**Comment by UndefinedBehaviour** [comment]
I think this one can be closed now.
