### ISSUE TITLE
[bug]: chrome 34 "Cannot redefine property: name"

### ISSUE THREAD

**Issue by wgundamj44** [Financial-Times/polyfill-library#319]
## What
Returned source code will cause `Cannot redefine property: name` error in chrome 34
## Details
#179 reported similar issue. The issue was closed as fixed, but actually it still exists in latest version. Try: 
Url: (https://polyfill.io/v3/polyfill.min.js?unknown=polyfill&flags=gated&features=default%2Ces2015) 

User Agent: `Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G900F-ORANGE Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36`

The returned bundle will cause `Cannot redefine property: name`  error in chrome 34.

Checking the error, it seems feature detect for `Function.Prototype.name` is broken.
Originally it was `'name' in Function.prototype && (function x() {}).name === 'x'` in source code, but becomes `"name"in Function.prototype&&"x"===function n(){}.name`  in returned bundle, causing redefinition of property.

**Comment by matrad** [comment]
@wgundamj44 any news on this - we've the same issue...

**Comment by JakeChampion** [comment]
this is now fixed :-)

**Comment by matrad** [comment]
@JakeChampion since this fix we've now another issue on Android 5.x / 6.x devices:

`Uncaught TypeError: Cannot read property addEventListener of null`

![Bildschirmfoto 2020-03-02 um 19 39 34](https://user-images.githubusercontent.com/660903/75706595-b85e8d00-5cbd-11ea-9162-3d31bcebd70c.png)

**Comment by JakeChampion** [comment]
@matrad That is fixed by https://github.com/Financial-Times/polyfill-library/pull/522 👍
