### ISSUE TITLE
[Bug] String.prototype.normalize seems to always be included

### ISSUE THREAD

**Issue by DannyvanHolten** [Financial-Times/polyfill-library#322]
# Bug report
## What
According to the mdn spec `String.prototype.normalize` should be supported without polyfills in general. However: if I include it in my call and open it in the newest chrome version I still get all the code related to `String.prototype.normalize`.

## Details

MDN Specs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize
Call: https://polyfill.io/v3/polyfill.js?features=String.prototype.normalize

To replicate: use the link mentioned above & open it in the newest chrome version (I am now using: 78.0.3904.70)

## Goal of this bug report

I would like to see the `String.prototype.normalize` for those browser that fully support this feature.

**Comment by chee** [comment]
ah, these are all asterisks: https://github.com/Financial-Times/polyfill-library/blob/8db31f38485465887f98cb8468092c68a247072f/polyfills/String/prototype/normalize/config.toml#L6-L22

**Comment by JakeChampion** [comment]
Pr for this --> https://github.com/Financial-Times/polyfill-library/pull/400
