### ISSUE TITLE
[bug] TypeError: undefined is not a constructor (evaluating 'new Intl.Collator(void 0,{numeric:!0,sensitivity:"base"})')

### ISSUE THREAD

**Issue by gkiely** [Financial-Times/polyfill-library#324]
**Type**: Bug report

## What
I'm seeing this error reported by android devices, I'm guessing it's a device that doesn't support Intl.

## Details
Expected behaviour:
Shouldn't be seeing this error.

Actual behaviour:
Browsers without Intl support are getting this error.

![image](https://user-images.githubusercontent.com/1948935/67861905-5fe46c80-fade-11e9-80af-399372bd3f36.png)

**Comment by JakeChampion** [comment]
@gkiely the polyfill.io url you are using does not include a locale to polyfill, that is likely the issue here. If you add `Intl.~locale.en-GB` or another locale name to the features parameter it should work :-)
