### ISSUE TITLE
[Feature request] Add Node.prototype.isConnected

### ISSUE THREAD

**Issue by ghost** [Financial-Times/polyfill-library#326]
## What
There's no `Node.prototype.isConnected` polyfill, it would be nice if I can use it from here to normalize my API usages.

## Details
  - I need to react to some changes, but only reflect to the UI when the container element of the changes is in the document (connected)
  - At the moment, `Node.prototype.isConnected` is missing on IE and Edge

An existing ponyfill could be found at https://www.npmjs.com/package/is-connected-node

**Comment by mhassan1** [comment]
@JakeChampion I see there was a [PR](https://github.com/Financial-Times/polyfill-library/pull/486) for this. Do you remember why it never left draft and was closed?

**Comment by JakeChampion** [comment]
I gave up on implementing the feature. I'm happy to review a PR which adds it 👍
