### ISSUE TITLE
URL in Edge

### ISSUE THREAD

**Issue by pavelloz** [Financial-Times/polyfill-library#33]
Looking at

https://caniuse.com/#feat=url
vs
https://polyfill.io/v2/docs/features/#URL

there are some inconsistencies.

Mainly Edge bothers me, but two versions of Safari in the middle of the line makes me thing it might be a bug.

**Comment by JakeChampion** [comment]
The data in caniuse is only for basic support of each feature, Safari and Edge do have some features of URL missings, particularly around handling of querystring construction and iteration support via Symbol.iterator.
