### ISSUE TITLE
[bug] As of v4.11.0, Array.from and Set polyfills (at least) now cause JS errors in IE11 when used in a web worker via importScripts

### ISSUE THREAD

**Issue by rognstad** [Financial-Times/polyfill-library#331]
## What

Prior to v4.11.0, including Set and Array.from polyfills in a worker context worked in IE11. After that release, including those features causes JS errors.

## Details
Two JS errors occur now in IE11:
1. `'window' is undefined`
2. `Could not complete the operation due to error 80020101`

Here's a demo: https://embed.plnkr.co/B3MWjla3dtkAI8XYo9p9/

**Comment by JakeChampion** [comment]
This is now fixed :-)
