### ISSUE TITLE
[feature request] Add nomodule polyfill

### ISSUE THREAD

**Issue by Cedric-ruiu** [Financial-Times/polyfill-library#336]
## What

Add nomodule polyfill

## Details

Safari 10.1 don't support nomodule attribut to import legacy code.

```html
<script src="legacy.js" nomodule></script>
```

## Additional information

You can find an example of implementation of a nomodule polyfill in this article [modern-script-loading](https://jasonformat.com/modern-script-loading/), see option 3.

Request make sense for you ?

**Comment by romainmenke** [comment]
I don't think this is something that can be reliably polyfilled through the polyfill service.
When loading the polyfill for `nomodule` from an separate file it isn't executed quickly enough to prevent loading.

Tested this in Safari 10.1 and when the patch is added in HTML it works. When loaded separately both bundles (`module` and `nomodule`) are loaded.

**Comment by JakeChampion** [comment]
Good point, this can only be polyfilled as inlined JavaScript, which we can't do in polyfill.io
