### ISSUE TITLE
ResizeObserver not responding IE11

### ISSUE THREAD

**Issue by NixonGit** [Financial-Times/polyfill-library#339]
[Bug]

## What

Attempting to polyfill ResizeObserver in IE11. I have checked the network response and there's no sign of it even though it has been requested...

 * Features requested: Array.prototype.map,IntersectionObserver,IntersectionObserverEntry,Math.hypot,ResizeObserver,default,es6

Any insight you may have would be greatly appreciated. Thanks

**Comment by JakeChampion** [comment]
Hi @NixonGit, could you please post the full user-agent string of the browser in which you see this bug, that will help me debug this issue for you.

If we are detecting the browser as IE 11 then it will get the polyfill for certain.

This urls shows that if we tell polyfill-library to pretend the browser is IE 11 that is does infact get IntersectionObserver -- https://cdn.polyfill.io/v3/polyfill.js?features=IntersectionObserver&ua=ie/11

**Comment by NixonGit** [comment]
Hi @JakeChampion we didn't experience a problem with IntersectionObserver. Its ResizeObserver that we couldn't see. The user agent string is Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko

Appreciate your help

**Comment by JakeChampion** [comment]
ResiveObserver is also served to IE/11 -- https://cdn.polyfill.io/v3/polyfill.js?features=ResizeObserver&ua=ie/11

Using the user-agent string you provided we can also see that it gets sent ResizeObserver -- https://cdn.polyfill.io/v3/polyfill.js?features=ResizeObserver&ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20WOW64;%20Trident/7.0;%20rv:11.0)%20like%20Gecko

Could you post the error message you are seeing and/or a screenshot of it please?

**Comment by NixonGit** [comment]
Here is the response from my network request in IE11 - I can see that resizeObserver appears in the features requested but I can't see it anywhere else in the response. I am using BrowserStack to test in IE11, could that be causing a problem? All the other Polyfills are fine. Thanks again for looking into it.

[resizeObserver_IE11_network-response.txt](https://github.com/Financial-Times/polyfill-library/files/4045652/resizeObserver_IE11_network-response.txt)

**Comment by JakeChampion** [comment]
Thanks for posting the response, I see the issue now.

You are using the older v2/polyfill.js endpoint which has really old and outdated polyfills.

We have v3/polyfill.js endpoint which has the most up to date polyfills and has ResizeObserver for IE 11.

As you can see with the links below, v2 does not give the polyfill and v3 does.
https://cdn.polyfill.io/v2/polyfill.js?features=ResizeObserverua=ie/11.0.0
https://cdn.polyfill.io/v3/polyfill.js?features=ResizeObserverua=ie/11.0.0

All you need to do is change from v2 to v3 :-)

Here is our migration guide for v2 to v3 -- https://github.com/Financial-Times/polyfill-service/blob/master/MIGRATION.md#migrating-from-v2-to-v3

**Comment by NixonGit** [comment]
Oh thats good news! I didn't realise there was a new version. Thanks for letting me know. Appreciate your help with it
