### ISSUE TITLE
Remove performance.now from dependencies of requestAnimationFrame.

### ISSUE THREAD

**Issue by sleagon** [Financial-Times/polyfill-library#34]
I think we should remove the performance from requestAnimationFrame's dependencies, because performance.now just adds a broken performance, which does not have measure and many other features. Many applications will check performance and use its once window.performance is not undefined. I think it is better to remove the performance.now from requestAnimationFrame and just use something like inline polyfill.

```javascript
        var nowOffset = Date.now();

	// use performance api if exist, otherwise use Date.now.
	// Date.now polyfill required.
	var pnow = function () {
		if (global.performance && typeof global.performance.now === 'function') {
			return global.performance.now();
		}
		// fallback
		return Date.now() - nowOffset;
	};
```

**Comment by JakeChampion** [comment]
Yes, we will accept this pull-request @sleagon

**Comment by sbinlondon** [comment]
Closing issue since the PR has been merged 👍
