### ISSUE TITLE
Update vulnerable dependency "diff" to v3.5.0

### ISSUE THREAD

**Issue by alexanderyarm** [Financial-Times/polyfill-library#341]
Github is warning about vulnerable dependency in our project cause of `polyfill-library`

## What
Github recommends to update `diff` dependency at least to version `3.5.0` and `polyfill-library` currently has `1.4.0`

![Screenshot 2019-12-19 at 17 16 32](https://user-images.githubusercontent.com/2443817/71189763-a440ed00-2283-11ea-93a0-8c5a59f212e5.png)

**Comment by JakeChampion** [comment]
done in https://github.com/Financial-Times/polyfill-library/pull/365
