### ISSUE TITLE
NodeList.prototype.forEach is not polyfilled for Opera Mobile <38

### ISSUE THREAD

**Issue by cravingsleep** [Financial-Times/polyfill-library#343]
##  What
The `NodeList.prototype.forEach` is not polyfilled for a user agent representing Opera Mobile <38.

## Details
Opera Mobile <38 does not natively support `NodeList.prototype.forEach`. The config needs updating so this is polyfilled.

**Comment by JakeChampion** [comment]
Thanks for the issue @cravingsleep, I've made a pull-request which fixes this --> https://github.com/Financial-Times/polyfill-library/pull/345
