### ISSUE TITLE
AbortController and AbortSignal polyfills

### ISSUE THREAD

**Issue by chrisfinch** [Financial-Times/polyfill-library#36]
Would be great if these can get polyfilled at some point;

https://developer.mozilla.org/en-US/docs/Web/API/AbortController

https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal

ScoutAsia is currently using this NPM package but would much prefer to use the polyfill-service instead!

https://www.npmjs.com/package/abortcontroller-polyfill

cc @JakeChampion

**Comment by JakeChampion** [comment]
Duplicate of #7, pull-request for this is https://github.com/Financial-Times/polyfill-library/pull/59
