### ISSUE TITLE
IE Polyfill unable to handle invalid URLs

### ISSUE THREAD

**Issue by FizzBuzz791** [Financial-Times/polyfill-library#4]
If I try to access an invalid URL in IE, such as localhost/?query=123%%%, the polyfill hits this line;
https://github.com/Financial-Times/polyfill-library/blob/1f5b5a1b72facaa89856de5da9afc3b85aaf7531/polyfills/URL/polyfill.js#L89

The error that comes back is "The URI to be decoded is not a valid encoding".

Seems to figure itself out in Firefox and Chrome, I haven't delved much further as to why it works for those browsers.

**Comment by Krinkle** [comment]
I can reproduce this and it is affecting Wikipedia as downstream user of this polyfill ([T106244](https://phabricator.wikimedia.org/T106244)).

The previous homemade URL parser we used was unable to deal with invalid UTF-8 in percent encoding in some graceful manner, whereas the `URL`  spec does. But upon switching to it, while it addressed the issue in modern browsers where we use it natively, it remains broken in browsers where we rely on the polyfill.

Standalone example: <https://codepen.io/Krinkle/full/gOXqZNK>.
```js
console.log(URL.toString()+''); var x;

try {
	x = new URL('https://example.org/y');
} catch (e) {
	x = '(caught) ' + e;
	console.error(e);
	console.log(e.stack);
} console.log('1:', x);

try {
	x = new URL('https://example.org/%96');
} catch (e) {
	x = '(caught) ' + e;
	console.error(e);
	console.log(e.stack);
} console.log('2:', x);

try {
	x = new URL('https://en.wikipedia.org/wiki/Special:Blankpage?from=en&to=es&campaign=article-recommendation&page=Apollo%96Soyuz_Test_Project');
} catch (e) {
	x = '(caught) ' + e;
	console.error(e);
	console.log(e.stack);
} console.log('3:', x);
```

In modern browsers:
```
function URL() { [native code] } 
1: URL { protocol: "https:", host: "example.org", pathname: "/y", .. }
2: URL { protocol: "https:", host: "example.org", pathname: "/%96", .. }
3: URL { protocol: "https:", host: "en.wikipedia.org", pathname: "/wiki/Special:Blankpage", search: "?from=en&to=es&campaign=article-recommendation&page=Apollo%96Soyuz_Test_Project" }
```

In IE 11 (Windows 10, BrowserStack):

```
funciton URL(url,base){if(!this instanceof URL)...}
1: https://example.org/y
2: https://example.org/%96
3: 
URIError: The URI to be decoded is not a valid encoding
  at Anonymous function
  at urlencoded_parse
  at URLSearchParams
  at URL
```
