### ISSUE TITLE
setPrototypeOf not supported in IE9 - IE10

### ISSUE THREAD

**Issue by shauns** [Financial-Times/polyfill-library#47]
The config for `Object.setPrototypeOf` refers to support for IEs 9-11 (https://github.com/Financial-Times/polyfill-service/blob/master/polyfills/Object/setPrototypeOf/config.json), but the source repo refers to IE 11+ (https://github.com/paulmillr/es6-shim/blame/master/README.md#L78) -- and indeed am finding errors using IE10 that boil down to the fill behaving incorrectly and causing incorrect inheritance behaviour in babel-transpiled code. (FYI Babel works around not having the `setPrototypeOf` method present.)

My workaround (for anyone else hitting the same issue) is to add `excludes=Object.setPrototypeOf` to my polyfill URL (so I'm not getting a bad fill added), and add `import "core-js/fn/object/set-prototype-of";` early in my code (so that I do have *a* fill for compatible browsers). This works okay so far.

I'm thinking that the fix here is to not fill `setPrototypeOf` for IE < 11, but I would imagine lots of other fills are relying on it... happy to submit a PR once steered!

**Comment by JakeChampion** [comment]
> Hi all, I stumbled upon this on my own research into setPrototypeOf polyfills, and can offer some further info.
> 
> [polyfill.io's setPrototypeOf](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Object/setPrototypeOf/polyfill.js) comes from the [es6-sham](https://github.com/paulmillr/es6-shim/blob/master/es6-sham.js#L58) of the [es6-shim library](https://github.com/paulmillr/es6-shim). While @shauns was correct that es6-shim [doesn't support IE<11](https://github.com/paulmillr/es6-shim/blame/master/README.md#L78), the "sham" was specifically created as a less-compliant option that would support older browsers including IE9-10 (sham info [here](https://github.com/paulmillr/es6-shim/pull/281), more info about non-compliance [here](https://github.com/paulmillr/es6-shim/pull/223#issuecomment-51696022)).
> 
> **The issue** is that the sham, for older browsers, _will not_ modify an object in-place - it needs to be reassigned. For instance:
> 
> ```js
> var foo = {a: 1};
> var bar = {b: 2};
> Object.setPrototypeOf(bar, foo);       // Doesn't work - bar is unchanged!
> bar = Object.setPrototypeOf(bar, foo); // Works, because bar is reassigned.
> ```
> 
> This can lead to some unexpected behaviour. Note that the polyfill does point out this issue in its comments:
> 
> ```js
> // NOTE:  This versions needs object ownership
> //        because every promoted object needs to be reassigned
> //        otherwise uncompatible browsers cannot work as expected
> ```
> 
> If anyone's looking into fixing the issue, it boils down to the use of [`createAndCopy`](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Object/setPrototypeOf/polyfill.js#L41) at line 41. The problem is any fix would give up something else - specifically, without recreating the object you can't "truly" preserve the prototype, and things like `instanceof` won't work correctly (but you could copy the prototype properties over, which might be "good enough").
> 
> For alternatives, @shauns mentioned using [core-js](https://github.com/zloirock/core-js), which is exclusively IE11+, and letting Babel take care of the rest. I believe Babel uses the "copy prototype properties over" approach. One other issue there is that subsequent changes to the prototype don't get reflected in the new object (more info [here](https://babeljs.io/docs/en/caveats#internet-explorer) and [here](https://babeljs.io/docs/en/babel-plugin-transform-proto-to-assign)). It's all a big mess, though I have tried to resolve that final issue [here](https://github.com/wesleytodd/setprototypeof/pull/10).
> 
> Good luck!

This is an excellent explanation of how our polyfill works and that it is not possible to create a perfectly spec compliant setPrototypeOf for IE 9 - 10
