### ISSUE TITLE
[bug] IE11 needs Object.keys for ES6 behavior

### ISSUE THREAD

**Issue by agriffis** [Financial-Times/polyfill-library#472]
## What
polyfill.io doesn't return polyfill Object.keys on IE11 by default, because it has an implementation. But the native implementation is the ES5 variant which breaks various libs, for example see https://github.com/reduxjs/redux-toolkit/issues/152

## Details
The Object.keys polyfill supports ES6 behavior:

https://github.com/Financial-Times/polyfill-service/issues/991
https://github.com/Financial-Times/polyfill-service/pull/1033

but it's not included in the bundle for IE11

The script tag I'm using is

```
<script src="https://polyfill.io/v3/polyfill.js?features=default,es5,es6,es7,es2017,console.debug,console.log,console.warn,fetch,HTMLPictureElement,Symbol|Gated"></script>
```

**Comment by agriffis** [comment]
Here's a bit more...

https://polyfill.io/v3/polyfill.js?features=Object.keys&ua=Mozilla%2F5.0+%28compatible%3B+MSIE+10.0%3B+Windows+NT+6.1%3B+WOW64%3B+Trident%2F6.0%29 sends the polyfill. That's using the IE 10 user-agent: `Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)`

https://polyfill.io/v3/polyfill.js?features=Object.keys&ua=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%3B+Trident%2F7.0%3B+rv%3A11.0%29+like+Gecko does not send the polyfill. That's using the IE 11 user-agent: `Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`

which is weird because the config shows it should apply to all IE versions:

https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/Object/keys/config.toml#L18

**Comment by agriffis** [comment]
Well sheesh, this has already been fixed in 1b237fb0

It's just not serving from polyfill.io yet

**Comment by JakeChampion** [comment]
this is now live :-)

**Comment by agriffis** [comment]
Thanks Jake!

Unfortunately, though, fixing this just reveals that the polyfill for `Object.getOwnPropertyNames` isn't ES6 compliant either. I'll file a separate issue.

**Comment by agriffis** [comment]
Looks like there's already an issue #218
