### ISSUE TITLE
Add String.prototype.trimStart, trimLeft, trimEnd, trimRight

### ISSUE THREAD

**Issue by jszczypk** [Financial-Times/polyfill-library#475]
Feature request - add polyfill for String.prototype.trimStart, trimLeft, trimEnd, trimRight

trimStart and trimEnd are not supported in IE, Edge and FF<61, Chrome<66
trimLeft and trimRight are not supported in IE
https://caniuse.com/#search=trimStart
https://caniuse.com/#search=trimEnd

Polyfill for trimStart
https://github.com/FabioVergani/js-Polyfill_String-trimStart

**Comment by JakeChampion** [comment]
Added in https://github.com/Financial-Times/polyfill-library/pull/95
