### ISSUE TITLE
ERROR in ./node_modules/graceful-fs/graceful-fs.js

### ISSUE THREAD

**Issue by hajar-alpha** [Financial-Times/polyfill-library#479]
Hi, I am new to this, I followed the steps created a file with the sample code of usage and I added this file to webpack mix, I get this
```
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs'
```
```
This dependency was not found:
* fs in ./node_modules/graceful-fs/graceful-fs.js

```
I tried some suggestions found on Internet, added some configuration to webpack to define 'fs' but this only generated other errors..

	- Chrome + 79
	- Desktop
	- Windows 10
	- Laravel Framework 5.8.37
	- Webpack Mix

**Comment by JakeChampion** [comment]
Hi @hajar-alpha 

Can you post a link to the page which had the steps you followed?
What is it you are trying to do?
Can you post some code which we can use to reproduce the issue?

Hopefully with the above information provided I will be able to help solve the problem you are seeing

**Comment by hajar-alpha** [comment]
The page is still local.

I installed polyfill-library and I have in webpack.min.js :

`const mix = require('laravel-mix');

mix.setPublicPath('../web/')
	.js('resources/js/app.js', 'assets/js').version();

mix.options({
    postCss: [
      require('autoprefixer'),
    ],
  });

mix.setPublicPath('../web/').js('polyfill-all.js', 'assets/js').version();
`
and in polyfill-all.js :

`const polyfillLibrary = require('polyfill-library');

const polyfillBundle = polyfillLibrary.getPolyfillString({
	minify: true,
	unknown:'polyfill'
}).then(function(bundleString) {
	console.log(bundleString);
});`

**Comment by JakeChampion** [comment]
`polyfill-library` does not work in the browser.

If you want to have a file which contains all the polyfills, you will need to create that file before you run your node server.

This code will make a file called `polyfill-all.js` which contains all the polyfills.
```js
const polyfillLibrary = require('polyfill-library');

const polyfillBundle = polyfillLibrary.getPolyfillString({
	minify: true,
	unknown:'polyfill'
	features: {
		'all': { flags: ['gated'] }
	}
}).then(function(bundleString) {
	fs.writeFileSync('polyfill-all.js', bundleString, 'utf-8');
});
```

I do recommend you not have a file which contains all polyfills, it will be very very very big. Instead I recommend you ask for only the polyfills you will need.

**Comment by hajar-alpha** [comment]
Thank you for your help, I will try to use only polyfills for Safari.
