### ISSUE TITLE
Documentation on how to add a polyfill

### ISSUE THREAD

**Issue by nickcolley** [Financial-Times/polyfill-library#498]
Type: feature request

## What
Adding documentation for contributors to the project so they know what's needed to add a new polyfill

## Details
I had a lot of very kind help from @JakeChampion but wondering if you'd welcome a pull request that documents some of the advice for example how the toml schema works and [other things mentioned in our discussion](https://github.com/Financial-Times/polyfill-library/issues/338).

You're welcome to close this issue depending on what you decide.

**Comment by JakeChampion** [comment]
That would be very much appreciated :-)
