### ISSUE TITLE
_DOMTokenList depedency not mentioned in Element.classList

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#506]
Bug report or question. Not sure yet, sorry

## What

`ReferenceError · _DOMTokenList is undefined`

## Details

We made this tool : [core-web](https://github.com/mrhenry/core-web/tree/master/packages/babel-plugin-core-web)

In short : it exposes this library as a babel plugin.

We ran into an issue where `_DOMTokenList` is undefined on older browsers.

The issue was first introduced here : https://github.com/Financial-Times/polyfill-library/commit/5d36d1921cfc8b22a473c62f87cc77fd40906292

The bug manifests itself in our code here :

https://github.com/mrhenry/core-web/blob/master/packages/core-web-generator/generate.js#L81-L88

https://github.com/mrhenry/core-web/blob/master/packages/core-web-generator/generate.js#L81

`meta.dependencies` is the `dependencies ` value in the `config.toml` file of a polyfill.

We treat the dependencies list as a complete list and `_DOMTokenList` is not included there, so an import statement is not added.

Is this a bug on our end and do we need to check the dependencies in a recursive manner? 

Or does `_DOMTokenList` need to be added to the `classList` `config.toml` ?

**Comment by JakeChampion** [comment]
> Is this a bug on our end and do we need to check the dependencies in a recursive manner?

Yes, you would need to do a recursive check.

**Comment by romainmenke** [comment]
Thank you for checking!
