### ISSUE TITLE
[bug]: Intl returning broken script in v3 service

### ISSUE THREAD

**Issue by schrags08** [Financial-Times/polyfill-library#507]
## What
When loading the Intl polyfill via the v3 service in IE11, it returns broken JS.

## Details
Browser: IE11
Device: Windows 10

How to Reproduce:
Load the polyfill in IE11 via: `<script src="https://polyfill.io/v3/polyfill.js?flags=gated&features=Intl"></script>`.

The console is reporting an error in polyfills.js: "Locale 'af-NA.js' is not well-formed."

**Comment by JakeChampion** [comment]
This is now fixed and live on polyfill.io, sorry for the bug which was introduced.
