### ISSUE TITLE
[bug] smoothscroll polyfill is never executed

### ISSUE THREAD

**Issue by rasteiner** [Financial-Times/polyfill-library#508]
## What
The whole smoothscroll polyfill is wrapped in this:
```js
if (!(!0)) {
 /* polyfill */
}
```
Which is boolean for `if(false) {}`. Therefore it's never run.

## Details
I'm not familiar with this repo, but I guess commit number https://github.com/Financial-Times/polyfill-library/commit/dc90a49d958bc8f8b4baa70297aeffcdc539edca is the culprit.
I also guess that the content of the polyfill [detect.js](https://github.com/Financial-Times/polyfill-library/blob/dc90a49d958bc8f8b4baa70297aeffcdc539edca/polyfills/smoothscroll/detect.js) should be `false` and not `true` (I've made a little PR in case this is correct)

**Comment by JakeChampion** [comment]
This was fixed via https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/smoothscroll/detect.js and released in v3.52.0
