### ISSUE TITLE
[bug] Intl feature detection is broken since today

### ISSUE THREAD

**Issue by ic1011** [Financial-Times/polyfill-library#509]
https://cdn.polyfill.io/v3/polyfill.min.js?features=Intl.~locale.en-GB%2CIntl.~locale.de-CH&flags=gated%2Calways returns [BCP 47 language tags](http://tools.ietf.org/html/rfc5646) in wrong format:

```javascript
/* Disable minification (remove `.min` from URL path) for more info */

(function(self, undefined) {if (!('Intl' in self && 
 Intl.Collator && 
 Intl.DateTimeFormat && 
 Intl.NumberFormat && 
 Intl.NumberFormat.supportedLocalesOf && 
 Intl.Collator.supportedLocalesOf('af-NA.js').length === 1 && 
 Intl.DateTimeFormat.supportedLocalesOf('af-NA.js').length === 1 && 
 Intl.NumberFormat.supportedLocalesOf('af-NA.js').length === 1 && 
 Intl.Collator.supportedLocalesOf('af-ZA.js').length === 1 && 
 Intl.DateTimeFormat.supportedLocalesOf('af-ZA.js').length === 1 && 
 Intl.NumberFormat.supportedLocalesOf('af-ZA.js').length === 1 && 
 Intl.Collator.supportedLocalesOf('af.js').length === 1 && 
``` 

And as a result, all browsers return similar error:

```javascript
Uncaught RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at <anonymous>:1:15
```

The correct language tags format must not include the '.js' suffix. For example, 'af-ZA.js' is incorrect and 'af-ZA' is correct.

It was working fine for months until today.

Maybe something needs to be changed. Any tips?

**Comment by chee** [comment]
hey, @ic1011! thanks for the report!

From what I can see this should have been fixed in [this PR](https://github.com/Financial-Times/polyfill-library/pull/499) which hasn't yet been released. 

I'll see about getting that released :)

**Comment by ic1011** [comment]
Thanks alot, @chee!

Sorry I opened the issue in the wrong repository. I hope it gets released soon!

**Comment by JakeChampion** [comment]
This is now fixed and live on polyfill.io, sorry for the bug which was introduced.
