### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by viT-1** [Financial-Times/polyfill-library#511]
Got error in Chrome 80.0.3987.87, Opera 66.0.3515.72, Firefox 72.0.2
`Uncaught TypeError: Cannot read property 'addEventListener' of null` with script
```
<head>
<script src="https://cdn.polyfill.io/v3/polyfill.min.js?flags=always,gated&excludes=Symbol,Symbol.iterator,Symbol.species&features=default" />
...
</head>
```

on 81 line: `return document.body.addEventListener("focusin",function() n=!0}),document.body.dispatchEvent(new Event("focusin")),n})()`

May be it happens when body is not loaded yet.

IE11 has no error.

**Comment by JakeChampion** [comment]
Pr for this --> https://github.com/Financial-Times/polyfill-library/pull/522
