### ISSUE TITLE
Supporting future roadmap of user agents (detecting browser feature list)

### ISSUE THREAD

**Issue by uzairfaisal** [Financial-Times/polyfill-library#516]
## What

Google is [phasing out user-agents](https://www.zdnet.com/article/google-to-phase-out-user-agent-strings-in-chrome/) in favour of [client hints](https://wicg.github.io/ua-client-hints/). Let's develop a going-forward strategy for future browsers since the library primarily depends on user-agents.

## Details
Either use the new unified user-agent values for future browsers or client hints to determine set of features supported/unsupported for polyfilling purposes.

## Additional information
Since prior browser versions will keep existing user-agents, I don't expect this library to break for previous browser versions.

This may be too early to discuss now but good to get a conversation going around feasibility of using this library for future browser versions based on the current information provided.

**Comment by JakeChampion** [comment]
The plans for `sec-ch-ua` is we will sniff `sec-ch-ua` first and fallback to `sec-ch-ua`, we would also add `sec-ch-ua` to the `vary` header response for caching correctly. That is all we need to do to suppor it.

However, Client hints is a proposal and the Sec-CH-UA-* clinet hints proposal is being reviewed by the W3C TAG. It may not be something that ends up being implemented by all the browsers or by any of them.
