### ISSUE TITLE
[bug] Element.prototype.matches for Edge 12-14

### ISSUE THREAD

**Issue by plesiecki** [Financial-Times/polyfill-library#517]
Hello 👋 

I've noticed regression after #444. According to https://caniuse.com/#search=matches `matches` is supported but with prefix `ms` 🙃 

I wonder how we should handle this prefix case? Just change version in config?

Peace ✌️

**Comment by JakeChampion** [comment]
Fixed via #518

**Comment by plesiecki** [comment]
Thanks ✌️
