### ISSUE TITLE
Polyfill String.prototype.normalize

### ISSUE THREAD

**Issue by Justkant** [Financial-Times/polyfill-library#52]
Hi,
It could be useful to cover [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/String/normalize#Browser_compatibility) as well
I found this [package](https://github.com/walling/unorm) which seems to implement the correct polyfill but it hasn't been updated in a long time.
What's your opinion on that ?

**Comment by JakeChampion** [comment]
PR for this work https://github.com/Financial-Times/polyfill-library/pull/105

**Comment by Justkant** [comment]
Thanks for the PR

**Comment by JakeChampion** [comment]
This has now landed in master via #105
