### ISSUE TITLE
feature-request: Test that feature detects are not always true or false

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/polyfill-library#520]
We've had some feature detects which use IIFE (immediately invoked function expressions) but forgot to invoke them, which meant they were returning a function, and a function is always truthy.

E.G.
```js
'getOwnPropertyNames' in Object && (function() {
    try {
        Object.getOwnPropertyNames(1);
        return true;
    } catch (e) {
        return false;
    }
})
```

Notice that the function is not executed (no `()` at the end).

We need to have a test which checks each `detect.js` file is not always evaluated to true or to false. If we can also have it prove no errors will be thrown, that would be incredible.

I know sonarlint is a tool which can prove an expression will always be true or false, perhaps there is a lighter tool/solution we could use though?

_Originally posted by @JakeChampion in https://github.com/Financial-Times/polyfill-library/issues/218#issuecomment-592972121_

**Comment by romainmenke** [comment]
Have been playing around with this and it produces some interesting results.
Found some broken detects and possibly some polyfill issues : 

https://github.com/romainmenke/polyfill-library/pull/38

Tried a really simplistic approach where I just added `()` after a detect source. This already caught a couple of cases.
Combined with testing for `false` when the polyfill isn't loaded it covers quite a bit of this issue.

Going to poke it a bit more before opening a PR.
