### ISSUE TITLE
navigator.sendBeacon does not fail silently

### ISSUE THREAD

**Issue by jackmellis** [Financial-Times/polyfill-library#523]
Bug

## What
If sendBeacon fails to send fails silently. The polyfilled version throws an error.
This came out of testing an app that was sending google analytics directly via sendBeacon. A user had IE11 set to strict privacy, which blocked the request. The sendBeacon polyfill threw an error which caused the entire page to crash

## Details
This came out of testing an app that was sending google analytics directly via sendBeacon.  
A user had IE11 set to strict privacy, which blocked the request. The sendBeacon polyfill threw an error which caused the entire page to crash

**Comment by JakeChampion** [comment]
Hi @jackmellis, thank you for the good issue here :-)

The pull-request to fix this issue is https://github.com/Financial-Times/polyfill-library/pull/524 👍
