### ISSUE TITLE
HTMLCanvasElement.toBlob is not served in Mobile Safari 10

### ISSUE THREAD

**Issue by gdorsi** [Financial-Times/polyfill-library#53]
The problem can be tested against this UA:
 - `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1`

I have reproduced the bug with iPhone 6s Plus, IOS 10.3

**Comment by JakeChampion** [comment]
We need to confirm that the polyfill is not configured to already served safari 10.3 as well as edge 14.

We can do that by viewing the configuration file here --> https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/HTMLCanvasElement/prototype/toBlob/config.json

**Comment by JakeChampion** [comment]
It looks like we have already done this work but forgot to close the issue --> https://github.com/Financial-Times/polyfill-library/commit/99bfd794ffae936cfc2ad59a787af875c1b08952
