### ISSUE TITLE
Feature Request: Navigator.permissions API polyfill?

### ISSUE THREAD

**Issue by kennsorr** [Financial-Times/polyfill-library#537]
I noticed that [Navigator.permissions](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/permissions) property is not supported in IE or Safari. Would it be possible to add this as a polyfill?

**Comment by JakeChampion** [comment]
We won't be adding a polyfill for `Navigator.permissions`, from what I understand about the Permissions API it is no possible to implement a polyfill for it which is useful.
