### ISSUE TITLE
Update yaku version to v1.0.0

### ISSUE THREAD

**Issue by allyraza** [Financial-Times/polyfill-library#538]
Update yaku version v1.0.0 

## What

I raised an issue  in yaku issue tracker for support for allSettled which was release yesterday can we please update the version

## Details

https://github.com/ysmood/yaku/issues/62

**Comment by JakeChampion** [comment]
It looks like this was done in https://github.com/Financial-Times/polyfill-library/pull/819 but we forgot to close this issue
