### ISSUE TITLE
IE11 Array.from on List from immutable.js

### ISSUE THREAD

**Issue by dmitin-bv** [Financial-Times/polyfill-library#54]
I have React application with Redux-form.
Looks like immutable.js is used internally by React (or Redux).
Originally I was going to report an issue for immutable.js,
but I realized that issue is reproducible only when polyfill is used (under IE11).
Application works fine under FireFox (without polyfill).

Under IE11 (with polyfill) next line in parseIterableLike() looks to be a problem
```
var arr = parseIterable(usingIterator(items));
```

That line is called from Array.from polyfill.
In my case it should convert List from immutable.js to Array, but in fact original List is returned.
As result "items" parameter is assigned to arrayLike as is (without conversion to Array), because in parseIterableLike() at the end "arr" is false.
```
var arrayLike = Object(parseIterableLike(items));
```

Because of no conversion in line below I receive 0, since arrayLike.length is undefined (List from immutable.js has only correct size property)
```
var len = toInteger(arrayLike.length);
```

Even after manual changing "len" to correct size of list (using debugger), at the end I receive array of "undefined" items, since in next line "[]" operator doesn't work (because arrayLike is not an array)
```
kValue = arrayLike[k];
```

**Comment by JakeChampion** [comment]
This has been released and looks to be fixed now :-)
