### ISSUE TITLE
[Bug] Safari 10.3.3 - Cannot redefine property: flat

### ISSUE THREAD

**Issue by FreshRob** [Financial-Times/polyfill-library#551]
- Browser: Safari 10.3.3
- Os: iOS
- Error: Cannot redefine property:flat

**Error as described in NewRelic**
`
Cannot redefine property:flat
at Function.defineProperty
at CreateMethodProperty in https://cdn.polyfill.io/v3/polyfill.min.js
Line 3 : Column 880
at anonymous in https://cdn.polyfill.io/v3/polyfill.min.js
Line 3 : Column 6263
at anonymous in https://cdn.polyfill.io/v3/polyfill.min.js
Line 3 : Column 30143
`

**Our polyfill.io url**
`https://cdn.polyfill.io/v3/polyfill.min.js?features=default,es2015,es2016,es2017,fetch,Promise.prototype.finally,NodeList.prototype.forEach,NodeList.prototype.%40%40iterator,Array.prototype.flat,IntersectionObserver`

**Comment by JakeChampion** [comment]
Safari added Array.prototype.flat in version 12. The issue you are seeing looks to be that something else has already polyfilled Array.prototype.flat before the polyfill.io polyfills have loaded. Are you loading other polyfills on the same page?
