### ISSUE TITLE
Feature Request: TextEncoder / TextDecoder

### ISSUE THREAD

**Issue by Menci** [Financial-Times/polyfill-library#554]
## What
Seems polyfill.io doesn't support TextEncoder and TextDecoder.

## Details
https://developer.mozilla.org/zh-CN/docs/Web/API/TextEncoder

**Comment by JakeChampion** [comment]
Duplicate of https://github.com/Financial-Times/polyfill-library/issues/207

**Comment by Menci** [comment]
Oh no why I didn't see any issues when I search for TextEncoder.
