### ISSUE TITLE
CSS.supports polyfill is missing

### ISSUE THREAD

**Issue by ertugrulcetin** [Financial-Times/polyfill-library#563]
It would be nice to have `CSS.supports` polyfill, yesterday our production went down due to this polyfill :) Here is the souce code: https://github.com/termi/CSS.supports

**Comment by MoritzLoewenstein** [comment]
I am trying to implement this, there seem to be a few different, possibly outdated polyfills out there:
1. https://github.com/termi/CSS.supports
2. https://github.com/vevlins/CSS.supports (fork of 1.)
3. https://gist.github.com/codler/03a0995195aa2859465f
4. Complete Replacement for CSS.supports and @supports in css https://github.com/kjarmicki/fq-polyfill
The third one is by far the shortest, I will check for spec compliance.

Optimal would be a polyfill which also utilizes earlier implementation (see [here](https://caniuse.com/#feat=css-supports-api) )

**Comment by ertugrulcetin** [comment]
@JakeChampion when will this be available on http://polyfill.io ?

**Comment by JakeChampion** [comment]
PR to update polyfill.io -- https://github.com/Financial-Times/polyfill-service/pull/2211
