### ISSUE TITLE
Yandex on iOS not aliased properly

### ISSUE THREAD

**Issue by salzhrani** [Financial-Times/polyfill-library#58]
Bug

## What

Yandex on iOS uses webkit as most browsers on iOS do.
## Details

It is not polyfilled correctly

I made a PR on the service repo and would like to move it here.
https://github.com/Financial-Times/polyfill-service/pull/1812

**Comment by JakeChampion** [comment]
The repo for useragent detection already has an issue open for this --> https://github.com/Financial-Times/polyfill-useragent-normaliser/issues/6
