### ISSUE TITLE
matchMedia : undefined is not an object (evaluating 'this.addListener.listeners.indexOf')

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#623]
https://github.com/Financial-Times/polyfill-library/blob/83e74edfe2c944cebd28a1beddf30d6ffbdfbc18/polyfills/matchMedia/polyfill.js#L47

`undefined is not an object (evaluating 'this.addListener.listeners.indexOf')`

Will try to replicate in a test and update this issue.

|   | browser details  |
| --- | --- |
| browserName | Mobile Safari |
| browserVersion | 10.0.0 |
| locale | nl-BE |
| osName | iOS 10.3 |
| userAgent | Mozilla/5.0 (iPad; CPU OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) | Version/10.0 Mobile/14G61 Safari/602.1 |

**Comment by JakeChampion** [comment]
Thanks for the issue, this should fix the bug -- https://github.com/Financial-Times/polyfill-library/pull/625

**Comment by romainmenke** [comment]
Nice! Was just about to update my PR with exactly the same code change as a fix. :)
