### ISSUE TITLE
Fetch is (incorrectly) polyfilled on iOS13

### ISSUE THREAD

**Issue by bakura10** [Financial-Times/polyfill-library#628]
## What

I have figured out that (apparently recently) fetch is polyfilled on iOS13 while this is natively supported. The fetch polyfill replaces the native implementation that seems to cause some quirks here and there.

## Details

Simply open this URL on iOS 13: https://cdn.polyfill.io/v3/polyfill.min.js?unknown=polyfill&features=fetch

iOS 13 should return nothing, but the whole polyfill is returned.

**Comment by romainmenke** [comment]
This should be fixed. Polyfill is no longer loaded in modern Safari (tested in 14)
