### ISSUE TITLE
Intl.PluralRules not being served to Edge < 18

### ISSUE THREAD

**Issue by glsignal** [Financial-Times/polyfill-library#633]
## What

Intl.PluralRules is not supported, and the polyfill is not loaded, in Edge <18

## Details

Based on the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules#Browser_compatibility) Edge has support for Intl.PluralRules in version 18 onwards

Loading `https://polyfill.io/v3/polyfill.min.js?features=Intl.PluralRules.%7Elocale.en` in Edge 17 returns an empty script, I would expect a polyfill to be loaded instead

## Additional Details

It might be as simple as applying the following, happy to open a PR if that will help!

```diff
diff --git a/polyfills/Intl/PluralRules/config.toml b/polyfills/Intl/PluralRules/config.toml
index d68d9e79..3d6c0359 100644
--- a/polyfills/Intl/PluralRules/config.toml
+++ b/polyfills/Intl/PluralRules/config.toml
@@ -9,6 +9,7 @@ notes = [
 
 [browsers]
 android = "<63"
+edge = "<18"
 ie = "9 - *"
 ie_mob = "9 - *"
 firefox = "<58"
```

---

Thank you for your work on this project ❤️

**Comment by JakeChampion** [comment]
Hi @glsignal, yes that change is all it should take, if you want to open a pull-request for that change then I can review, approve and merge it :-)

**Comment by longlho** [comment]
this can be closed I assume?

**Comment by JakeChampion** [comment]
Yes, thanks for checking this @longlho :-)
