### ISSUE TITLE
[bug] Documentation for features including a locale is incorrect

### ISSUE THREAD

**Issue by dantman** [Financial-Times/polyfill-library#650]
The documentation for `Intl.PluralRules` states:
```Locales must be specified separately by prefixing the locale name with `Intl.PluralRules~locale`, eg `Intl.PluralRules~locale.en-GB`.```

However [Intl.PluralRules~locale.en-GB](https://polyfill.io/v3/polyfill.js?features=Intl.PluralRules~locale.en-GB&flags=always) doesn't resolve to a valid polyfill.

This is the same for `Intl.RelativeTimeFormat.~locale.*` as well.

In practice none of the `en` subtags have features, it's only `en`.

**Comment by longlho** [comment]
So this depends on the polyfill. E.g `Intl.PluralRules` locales do not vary per region subtag but `Intl.NumberFormat` and friends do. `Intl.RelativeTimeFormat` also rolls up all regions within a lang into a single file.
The only way to know is to check like https://unpkg.com/browse/@formatjs/intl-relativetimeformat@5.2.6/dist/locale-data/

**Comment by chee** [comment]
@JakeChampion do we want to improve the documentation here, or is this working as expected?

**Comment by JakeChampion** [comment]
This is no longer true for `Intl.RelativeTimeFormat` -- we have the locale subtags for that feature.

I've made a pull-request to update the notes for Intl.PluralRules -- https://github.com/Financial-Times/polyfill-library/pull/1084
