### ISSUE TITLE
Fetch polyfill is no longer spec compliant

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/polyfill-library#651]
## What
The fetch polyfill is no longer actively maintained and is no longer spec compliant in a number of ways.

## Details
There are a number of [issues/PRs to fix spec non-compliance](https://github.com/github/fetch/issues) but nothing has been merged for a long while and the last release was in September 2018. I was about to start the npm disputes process (which despite the name 'dispute' is actually just the process to transfer ownership) with an eye to possibly transferring ownership to FT if github weren't interested in continuing maintenance. I was surprised to find, @JakeChampion, that you are already a co-owner of the npm package (though with no rights to the repo I guess).

Has the polyfill service ever taken over an unmaintained polyfill in the past? If so, what next steps would you recommend?

(aside) There is a sweet irony in that, going by issues raised on fetch-mock, IE11/Edge are the main browsers in need of the polyfill, and these are Microsoft's, who now own github, who look like they have abandoned the polyfill.

**Comment by JakeChampion** [comment]
@wheresrhys I do have permission on the repo and the package :-)

**Comment by JakeChampion** [comment]
>Has the polyfill service ever taken over an unmaintained polyfill in the past? If so, what next steps would you recommend?
Yes, I have already taken on the polyfill but I seem to have forgotten to 'watch' the repo for issues. Sorry about that 😔

**Comment by chee** [comment]
going to close this as it's an issue about a project with its own issue tracker
