### ISSUE TITLE
Replace smoothscroll with seamless-scroll-polyfill

### ISSUE THREAD

**Issue by jamesarosen** [Financial-Times/polyfill-library#657]
Possibly a bug?

## What
The current `smoothscroll` library, [smoothscroll-polyfill](https://www.npmjs.com/package/smoothscroll-polyfill), doesn't support the `block` and `inline` options. iamdustan/smoothscroll#87 suggests that it's no longer maintained. [seamless-scroll-polyfill](https://www.npmjs.com/package/seamless-scroll-polyfill) is a better-maintained fork that complies with more of the spec.

**Comment by jamesarosen** [comment]
I'm happy to attempt a PR if there's interest.

**Comment by JakeChampion** [comment]
@jamesarosen yes please :-)
