### ISSUE TITLE
[feature-request] Proxy polyfill

### ISSUE THREAD

**Issue by dorongutman** [Financial-Times/polyfill-library#670]
## What

Can you please add a polyfill for Proxy?

I know there's Financial-Times/polyfill-service#2004 but it seems https://github.com/GoogleChrome/proxy-polyfill is a good polyfill that at least provides the main capabilities of the Proxy object.

**Comment by JakeChampion** [comment]
Hi, I'm sorry to say that proxy is not included in polyfill-library and it likely will not be included as it is impossible to implement a polyfill for proxy that works correctly.
