### ISSUE TITLE
[Feature Request] Given a browser matrix, output the suite of polyfills per browser for every version that satisfies the matrix

### ISSUE THREAD

**Issue by longlho** [Financial-Times/polyfill-library#671]
## What
My use case is that I want an API that takes in a browser matrix (e.g `ie11, chrome76`) and a list of features and give me a polyfill bundle for every browser (and version) that needs it. For example, if I give it `ie11, chrome60` with features `Intl.RelativeTimeFormat` it'd give me:
- `ie11.js` that has `Intl.getCanonicalLocales`, `Intl.PluralRules` & `Intl.RelativeTimeFormat`
- `chrome62.js` that has `Intl.getCanonicalLocales`, `Intl.PluralRules` & `Intl.RelativeTimeFormat`
- `chrome71.js` that has `Intl.RelativeTimeFormat`

## Details
This can be done with brute force incrementing browser version per browser up to latest but I'm wondering if the library can support this natively or if anyone's asked for it.

Thanks!

**Comment by romainmenke** [comment]
We wanted to generate client side feature detection and ended up using `caniuse` data.

We took the known browsers from `caniuse` and looped them (kinda brute forced it).
We used `semver` to see if the feature (config file -> browsers) satisfies the browser from `caniuse`.

Maybe this feature does not need to be included in this package?
Might be better for maintenance as `caniuse` publishes a lot :)

Main logic :

https://github.com/mrhenry/core-web/blob/main/packages/core-web-generator/generate-client-side-detectors.js

Result : 

https://github.com/mrhenry/core-web/blob/main/packages/core-web/helpers/__client-side-detectors.js

**Comment by JakeChampion** [comment]
We wouldn't implement this as part of polyfill-library, it would have to be a separate package.

We do have a package which does something similar called [create-polyfill-service-url](https://www.npmjs.com/package/create-polyfill-service-url). It is a Node.js command-line application for analysing your JavaScript file and generating a https://polyfill.io URL based on all the features that are being used from within the JavaScript file, it also adheres to a browserslist configuration.
