### ISSUE TITLE
Intl : locale data nu must be an object

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#676]
With the latest update to `Intl` dependencies we are seeing some errors :

`locale data nu must be an object`

We haven't been able to pinpoint the exact change in the formatjs that introduced the issue.

Our test code :

```
const format = new Intl.RelativeTimeFormat("en", { style: "narrow" });
const expected = "in 3 qtrs.";
const actual = format.format(3, "quarter");
assert.equal(actual, expected);
```

Will try to verify against polyfill.io
Maybe it's just us.

**Comment by longlho** [comment]
looks like you need to give it the `en` locale-data. Polyfills no longer ships w/ `en` by default because it doubles the payload for all other locales

**Comment by romainmenke** [comment]
🤔 would that not have been a breaking change? Maybe I missed something :)

**Comment by longlho** [comment]
It's a breaking change from the formatjs side (I think major version was bumped) but IDK about this library since it combines so many 3rd-party deps.

**Comment by romainmenke** [comment]
You did put me on the right track. We are including the `en` locale data, but we are missing some other bits.
Adding `Intl.NumberFormat.~locale.en` gives us a different error which should mean that this was at least one thing we needed to include.

The [docs](https://formatjs.io/docs/polyfills/intl-relativetimeformat) indeed state we need the number format polyfill :) .

```
const format = new Intl.RelativeTimeFormat('en', { style: 'narrow' });
const expected = 'in 3 qtrs.';
const actual = format.format(3, 'quarter');
assert.equal(actual, expected);
```

For that code we now import this list :

<img width="305" alt="Screenshot 2020-06-26 at 08 17 41" src="https://user-images.githubusercontent.com/11521496/85826978-89e15200-b785-11ea-9f6b-f5bfa9f7203e.png">

A first quick test seems to pass!
Thank you for taking a look 🙇

**Comment by romainmenke** [comment]
I am thinking now that this is a breaking change for this package too.

To make it non-breaking the `en` locale should be loaded by default as was the behaviour before this change.

**Comment by longlho** [comment]
ping @JakeChampion ?

**Comment by JakeChampion** [comment]
@longlho just to confirm I understand, previous versions included the `en` locale by default and the current version does not, is that correct?

If so, I think we would constitute that as a breaking change in the API and would be need to increase the major version of polyfill-library and write a migration guide for the change.

**Comment by longlho** [comment]
I believe so yes.

**Comment by romainmenke** [comment]
Correct, but this goes for all polyfills.

For example `RelativeTimeFormat` has `NumberFormat` as a dependency, but the `en` locale for `NumberFormat` is also no longer loaded by default.

This case is more complicated for users to resolve as they might not have known they depended on `NumberFormat` when loading the `RelativeTimeFormat` polyfill. The error message also doesn't help much in figuring out which polyfill is missing which locale.

**Comment by longlho** [comment]
is there a way to declare locale dependency within polyfill-library?

**Comment by longlho** [comment]
this can be closed imo

**Comment by JakeChampion** [comment]
PR to fix this issue is -- https://github.com/Financial-Times/polyfill-library/pull/818

**Comment by romainmenke** [comment]
fix confirmed! :)
