### ISSUE TITLE
Add AbortController and AbortSignal polyfill

### ISSUE THREAD

**Issue by DavidBruant** [Financial-Times/polyfill-library#7]
A feature request

## What

polyfill.io does not provide polyfills for AbortController and AbortSignal\
consequently, it also does not provide support for [abortable fetch](https://developers.google.com/web/updates/2017/09/abortable-fetch)

The feature exists and is supported in recent browsers, but [lacks support in (current at time of writing) Safari 12 and webkit-based mobile browsers like Chrome on iOS and Firefox on iOS](https://caniuse.com/#search=abort)

## Details

There is an [existing MIT-licenced polyfill](https://github.com/mo/abortcontroller-polyfill)

I'm not sure whether "AbortController + AbortSignal" and "abortable fetch" should be made into two separate issues

## Additional information

i love the polyfill.io project <3
thank you very very much

**Comment by Rendez** [comment]
I'd like to work on adding both the `AbortController` and `AbortSignal`, we also need it in the library. Is this something that might be in the scope of the core team? How can I get the ok-go?

**Comment by JakeChampion** [comment]
Hi @DavidBruant, thank you for the kind words!

We have a pull-request for this feature already :-) It is actively being worked on and I hope to have it in the next release of the polyfill-library. https://github.com/Financial-Times/polyfill-library/pull/59

**Comment by JakeChampion** [comment]
this was added in https://github.com/Financial-Times/polyfill-library/pull/59
