### ISSUE TITLE
(bug) matchMedia missing in ie9

### ISSUE THREAD

**Issue by white-room** [Financial-Times/polyfill-library#71]
## What
matchMedia polyfill is not present in ie9 bundle causing error "SCRIPT5022: matchMedia not present, legacy browsers require a polyfill" , even when explicitly listed as a feature in the request url:
https://cdn.polyfill.io/v3/polyfill.min.js?features=default%2CmatchMedia

## Details
Browser:
Windows 7 IE9 (9.0.8112.16421)

Reproduce with:
https://cdn.polyfill.io/v3/polyfill.min.js?features=default%2CmatchMedia

Results in:
SCRIPT5022: matchMedia not present, legacy browsers require a polyfill 

![image](https://user-images.githubusercontent.com/29190753/51852315-1793e600-22e3-11e9-8233-5c29d369afef.png)

**Comment by ilanbm** [comment]
Still happens

**Comment by JakeChampion** [comment]
PR for this --> https://github.com/Financial-Times/polyfill-library/pull/399
