### ISSUE TITLE
Bug Report: Comparing boolean to a number with strict operator can never be equal. 

### ISSUE THREAD

**Issue by thebpc** [Financial-Times/polyfill-library#714]
A bug Report

## What
Please see the description here (as it was found by www.DeepCode.ai): https://www.deepcode.ai/app/gh/financial-times/polyfill-library/def50f2afd152e393da405349d47eb6bf718d732/_/%2Fpolyfills%2FMap%2Fpolyfill.js/javascript%2Fdc%2FIncompatibleTypesInComparison/105/code

File: polyfills/Map/polyfill.js
LOC:105 with semantic flow defining the type of the variable from LOC: 472

## Details
a Video describing the problem https://www.youtube.com/watch?v=dc7gLhcuuHQ

## Additional information
Feel free to review all other suggestions on your repo, as well as subscribe the repository for continuous monitoring. It is fully free for OSS projects.
https://www.deepcode.ai/app/gh/financial-times/polyfill-library/def50f2afd152e393da405349d47eb6bf718d732/_/dashboard

**Comment by JakeChampion** [comment]
Thanks for the issue, this is fixed in https://github.com/Financial-Times/polyfill-library/commit/ae14a38ea77edea4443944346d4b3b32f70c7368
