### ISSUE TITLE
repo: versioning and breaking changes

### ISSUE THREAD

**Issue by krohrsb** [Financial-Times/polyfill-library#73]
## What
There seemed to be breaking changes between these two patch versions. Please correct me if I am mistaken.

https://github.com/Financial-Times/polyfill-library/compare/v3.27.1...v3.27.2

## Details
When upgrading, things broke unexpectedly (namely the constructor removal). I would expect patches to be backward compatible as per [semver](https://semver.org/).

Is it your intent to follow semver? If so, perhaps extra diligence on versioning things or even using tools such as [semantic-release](https://github.com/semantic-release/semantic-release) to automate that task.

## Additional information

I appreciate all the effort that has gone into this library and look forward to it's future!

**Comment by JakeChampion** [comment]
Yes sorry for this! The release 3.27.1 was the breaking change, 3.27.2 is reverting the break to go back to the expected interface of not having to construct the polyfill-library.

semantic-release looks really useful, I will look into adding something like that to this project :-)
