### ISSUE TITLE
[bug] `AbortController` polyfill is not served when `Element.prototype.matches` is also requested

### ISSUE THREAD

**Issue by SimpleCreations** [Financial-Times/polyfill-library#762]
## What
When I request `AbortController` polyfill from a browser that does not support it (i.e. IE11), it gets served as expected:
https://polyfill.io/v3/polyfill.js?features=AbortController

But when I add `Element.prototype.matches` to the same URL, `AbortController` request is ignored and the polyfill is not present in the response:
https://polyfill.io/v3/polyfill.js?features=AbortController%2СElement.prototype.matches

## Details
Tested in IE11, Safari 10.1, Chrome 49.

**Comment by JakeChampion** [comment]
>  [https://polyfill.io/v3/polyfill.js?features=AbortController%2СElement.prototype.matches](https://polyfill.io/v3/polyfill.js?features=AbortController%2%D0%A1Element.prototype.matches)

The `С` in the percent encoding in the URL you posted is a Cyrillic capital letter ES. It needs to be the Latin capital letter C.

When the percent encoding is corrected, it works as expected: https://polyfill.io/v3/polyfill.js?features=AbortController%2CElement.prototype.matches

A good way to check the encoding is correct is to use the `decodeURIComponent` function built into JavaScript.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1569131/88730650-7895b780-d12e-11ea-96e4-c993fc424e89.png">

**Comment by SimpleCreations** [comment]
Oh, I see! Must have had wrong keyboard layout when updating the URL. Thank you for the help and sorry for the inconvenience. Everything works now.
