### ISSUE TITLE
Intl polyfill loads all locale data files

### ISSUE THREAD

**Issue by czebe** [Financial-Times/polyfill-library#770]
## Details
Seems like the `aliases.json` file contains all `locale` files:

![image](https://user-images.githubusercontent.com/2728671/89784027-41ed7300-db18-11ea-84c4-cdad330a01e4.png)

The result is a huge polyfill string that causes both our server and the browser client to go out of memory (~ at about 700MB heap size as opposed to the normal 160MB with version `3.93.0` of `polyfill-library`.

What is the recommended way to only include the current `locale` data?

**Comment by JakeChampion** [comment]
Hi @czebe, that does look like the case, yes.

>What is the recommended way to only include the current locale data?

@longlho, would you be able to answer that at all? I ask as you have been working on the Intl polyfills a lot recently.

**Comment by longlho** [comment]
The recommended way is to load only the API & locales you need, so DateTimeFormat/NumberFormat...

**Comment by longlho** [comment]
looks like this is also a bug in aliases generation
