### ISSUE TITLE
 Promise.allSettled/Promise.any not supported in 'Promise' polyfill 

### ISSUE THREAD

**Issue by panda0603** [Financial-Times/polyfill-library#862]
## What

I can't seem to find support for Promise.allSettled and Promise.any in https://polyfill.io/v3/polyfill.min.js?features=Promise&flags=always

Do I have to use separate shim or polyfill library to support them? 
Where can I check the polyfill standards which polyfill-library is at the moment supporting? 
Thanks!

**Comment by JakeChampion** [comment]
These are not yet added to the polyfill-library

**Comment by panda0603** [comment]
any timeline for the support?
