### ISSUE TITLE
Request: polyfill for Proxy

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/polyfill-library#87]
Spec: https://tc39.github.io/ecma262/#sec-proxy-constructor
Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

Proxy is not 100% polyfillable and so we would need to include an explanation in the `notes` property of the config.json

We can likely use this polyfill: https://github.com/GoogleChrome/proxy-polyfill

We should include our own tests.js file and our own detect.js file.

**Comment by RiZKiT** [comment]
So, it's closed because it will not be implemented?

**Comment by JakeChampion** [comment]
We've not had interest from the community for `Proxy` and it is not possible to create a JavaScript implementation of `Proxy`.
There are 13 different `Proxy` "traps" and only 4 are implementable in JavaScript and even then those 4 are limited in how they can work. This polyfills lists all the caveats -- https://github.com/GoogleChrome/proxy-polyfill

We won't be including it in polyfill-library/polyfill.io due to those reasons above.
