### ISSUE TITLE
URLSearchParams silently fails for FormData under IE 11

### ISSUE THREAD

**Issue by wak45** [Financial-Times/polyfill-library#870]
## Details
<!--
- calling URLSearchParams, passing FormData: body: new URLSearchParams(new FormData(form)),

Code example:
      	fetch("/getdata.php", {
      		method: "POST",
	    	headers: {
    			"Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
  			},
			body: new URLSearchParams(new FormData(form)),
      	})

<!--
## Additional information

Problem is on the server side, I get php errors:

[13-Sep-2020 12:43:35 UTC] PHP Notice:  Undefined index: name in /getdata.php on line 4
[13-Sep-2020 12:43:35 UTC] PHP Notice:  Undefined index: address in /getdata.php on line 5

As far as I can check, the  URLSearchParams silently fails when passing FormData fails. 

Everything works fine on Chrome and Edge.

**Comment by lorenz** [comment]
In general using fetch with a URLSearchParams body produces an empty request on IE10 and 11. Both APIs are polyfilled there, so there seems to be an issue with them not interacting properly.

**Comment by romainmenke** [comment]
@lorenz Can you provide some code to reproduce and the polyfill.io url?

It doesn't have to be a real fetch request to a real endpoint.

**Comment by romainmenke** [comment]
https://github.com/github/fetch/blob/master/fetch.js#L8

Seems to be a loading order issue.
If I make `URL` a dependency on `fetch` it seems to work.

I don't think we wan't to do that, but maybe we can order the polyfills better?

<img width="413" alt="Screenshot 2021-07-17 at 20 12 11" src="https://user-images.githubusercontent.com/11521496/126046136-87e333b2-b4a0-441b-8098-7ab8b92abc6c.png">

tested with :

```js
if ('Request' in self) {
	it('works with fetch', function (done) {
		// https://github.com/Financial-Times/polyfill-library/issues/870
		new Request('#', { body: new URLSearchParams({ foo: 'baz' }), method: 'POST' }).text().then(function(x) {
			proclaim.equal(x, 'foo=baz');
			done();
		});
	});
}
```

In : `polyfills/URL/tests.js`

`http://bs-local.com:9876/test?includePolyfills=yes&always=no&polyfillCombinations=yes&feature=URL`

**Comment by lorenz** [comment]
My code is quite trivial, your test is already pretty much the same. Nice that you could already determine what's causing the problem, an ordering issue would indeed make sense.

**Comment by romainmenke** [comment]
@JakeChampion After some thought I think that adding `URL` to the dependency list of `fetch` would fix this issue for both uses of this package and users of polyfill.io.

Otherwise we would have to add new API in the config.toml files to express that some polyfills need to be ordered in a specific way.

If you agree with adding `URL` to the dependency list of `fetch` I'll submit a patch to resolve this.
Maybe you have a better idea :)

**Comment by JakeChampion** [comment]
> If you agree with adding `URL` to the dependency list of `fetch` I'll submit a patch to resolve this.

Sorry I didn't reply sooner -- I agree and I can see you've already got the pull-request in place 👍

**Comment by romainmenke** [comment]
That's ok :) We all have lot's to do!
