### ISSUE TITLE
Faster builds and watch command

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#887]
Feature suggestion

## What
The current `buildsources` script is heavily concurrent (async/Promise) but can be faster with parallelism (multiple node processes).

On my machine (macbook air 2020, 4 cores 8 threads) it takes about 70s to run.
As more features are added this will continue to rise.

This makes it harder to develop new features inside this repo.

How I currently work :

- make a change
- run command to build everything
- wait ±70s
- restart test server process
- refresh browser window with tests

## Suggested solution

With parallelism this goes down to about 40s. _This should be better on a beefier machine that doesn't throttle as much._

A simple watcher command can start by doing a full build after which only the desired feature is rebuild.
This command spawns a sub process for the test server that is killed and restarted automatically.

With the watcher changes are pretty much instant (<5s) compared to manual steps and a full rebuild.

```
npm run watch -- File

> polyfill-library@3.52.3 watch polyfill-library
> npm run clean && node tasks/updatesources && node tasks/buildsources/watchsource "File"


> polyfill-library@3.52.3 clean polyfill-library
> rimraf ./polyfills/__dist

Updating third-party polyfills...
_TypedArray: No change
...
...
WebAnimations: No change
Polyfills updated successfully
Doing a full build before starting watcher
Waiting for files to be written to disk...
Built successfully after 42s
Watching "File" ...
visit : http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=File
Test server listening on port 9876!
# changed a file here
server exited with exit code null
Waiting for files to be written to disk...
File built successfully after 3s
Test server listening on port 9876!
```

## Downside

The codebase becomes more complex. Any future changes would become more expensive and developers touching this script would need to have a basic understanding of parallelism in node.

## Next step

If this is something you are open to considering I will open a PR.

---------

_note :_

_I was curious and ported the script to go to compare performance and a full build then takes about 4 seconds.
This is maybe something to keep in mind in the long run that tooling does not need to be written in JS.
The experiment used [esbuild](https://github.com/evanw/esbuild) as a replacement for `uglify`._

**Comment by longlho** [comment]
u guys might wanna take a look at bazel. We migrated to bazel and selective build/CI build is mad fast

**Comment by romainmenke** [comment]
Cool!

That would require a complete overhaul of the build and test scripts. Knowing with absolute certainty what doesn't need to be tested after a code change is not a trivial issue to solve.

At the moment I was looking at improvements for build/test times (locally and CI) without actually changing any of the logic or dependencies.

**Comment by romainmenke** [comment]
fyi : https://github.com/romainmenke/polyfill-library/pull/34
That is the branch I am working on.

**Comment by JakeChampion** [comment]
@romainmenke This sounds like something we would very much like to have, thank you :-)

**Comment by JakeChampion** [comment]
> _note :_
> 
> _I was curious and ported the script to go to compare performance and a full build then takes about 4 seconds. This is maybe something to keep in mind in the long run that tooling does not need to be written in JS. The experiment used [esbuild](https://github.com/evanw/esbuild) as a replacement for `uglify`._

Does esbuild do all the things uglify does? If we use esbuild we need to set `--target=es5` otherwise it will minify into modern syntax which will fail in older browsers.

**Comment by romainmenke** [comment]
Unfortunately `esbuild` doesn't work well. Not all features can be transpiled to `es5`, which makes outputs fail in older browsers. I was mainly curious of what kind of performance the same build logic could have in a compiled language like `Go`.

Maybe if `esbuild` (or a similar project) matures enough it could be something to reconsider.

**Comment by JakeChampion** [comment]
> Unfortunately `esbuild` doesn't work well. Not all features can be transpiled to `es5`, which makes outputs fail in older browsers. I was mainly curious of what kind of performance the same build logic could have in a compiled language like `Go`.

We don't use any features in our polyfills which are not present in ES3 syntax, let alone ES5 or newer, so I would assume that this is a non-issue for polyfill-library to be able to use esbuild

**Comment by romainmenke** [comment]
> We don't use any features in our polyfills which are not present in ES3 syntax, let alone ES5 or newer, so I would assume that this is a non-issue for polyfill-library to be able to use esbuild

true!

This is where I ended up : https://github.com/romainmenke/polyfill-library-buildsources

Don't really remember the exact state of the code. It is almost a line-by-line port of the JS build script and I think it worked when I last touched it. But I definitely haven't done a thorough validation of all outputs.

**Comment by romainmenke** [comment]
Managed to get a run using the go-based build script : 

```
 • Browser: ie/10.0 Testing mode: targeted ✘ 1291 tests, 4 failures  286 seconds to complete
 • Browser: ie/11.0 Testing mode: targeted ✘ 1311 tests, 4 failures  296 seconds to complete
 • Browser: ie/8.0 Testing mode: targeted ✘ 1356 tests, 6 failures  416 seconds to complete
 • Browser: ie/9.0 Testing mode: targeted ✘ 1345 tests, 4 failures  310 seconds to complete
```

I think it might be possible to make it work with `esbuild` but I am not convinced it is worth it.
Switching would also require maintaining a second language (go) with it's own depencies.

Building all polyfills now takes ±20s in github actions. It's not nothing, but also not spectacular.
