### ISSUE TITLE
Publish new version with current changes since last release

### ISSUE THREAD

**Issue by TheDadi** [Financial-Times/polyfill-library#906]
Publish request

It would be nice if you could publish a new version of the lib, since there where bugfixes merged e.g. Intl for safari 14
which would be nice to have.

Thx

**Comment by JakeChampion** [comment]
This is done :-)
https://github.com/Financial-Times/polyfill-library/releases/tag/v3.97.0

**Comment by TheDadi** [comment]
thx @JakeChampion
