### ISSUE TITLE
String.fromCodePoint is a ES6 feature, but features=es6 not return String.fromCodePoint polyfill

### ISSUE THREAD

**Issue by yassh** [Financial-Times/polyfill-library#92]
Open following URL in IE 11:
https://polyfill.io/v3/polyfill.js?features=es6

Expected:
Content includes `String.fromCodePoint` polyfill, because `String.fromCodePoint` is a ES6 feature and IE 11 doesn't support it.

Actual:
Content doesn't include `String.fromCodePoint` polyfill.

**Comment by JakeChampion** [comment]
Fixed via https://github.com/Financial-Times/polyfill-library/commit/d67cbba2572295105efc808d98af6a13f491bbbf
