### ISSUE TITLE
StreamCache is not a true ReadStream

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#957]
`StreamCache` does not seem to implement `ReadStream` correctly.
When used together with `merge2` it all seems to work, but when trying to use it as a `ReadStream` directly, no `data|end|...` events are ever triggered.

https://github.com/Financial-Times/polyfill-library/blob/b0c8a8582dc164af25e834fc034e2db27c935516/lib/sources.js#L83

https://github.com/felixge/node-stream-cache/blob/master/lib/StreamCache.js

I ended up using this code to be able to read data from `StreamCache` without `merge2`.

```ts
type StreamCache = {
	pipe: (dest: StreamCacheDestination) => void
}

type StreamCacheDestination = {
	write: (chunk: Buffer) => void,
	end: () => void 
}

async function streamToString(stream: StreamCache) {
	return new Promise<string>((resolve) => {
		let out = '';
		stream.pipe({
			write: (chunk: Buffer) => {
				out += chunk.toString("utf-8");
			},
			end: () => {
				resolve(out);
			},
		});
	});
}
```

Would it be possible to return a true `ReadStream` from `streamPolyfillSource` on a next major release? (I think this is a breaking change). 

For now the jsdoc type signature could be updated.

**Comment by JakeChampion** [comment]
> Would it be possible to return a true `ReadStream` from `streamPolyfillSource` on a next major release? (I think this is a breaking change).

Yes, we can do that, if you are able to implement this change I'd be happy to review and release it.
