### ISSUE TITLE
Intl.~locale.en-CA throwing on IE11 (other en-* work as expected)

### ISSUE THREAD

**Issue by aronwoost** [Financial-Times/polyfill-library#958]
Bug report

## What
`Intl.~locale.en-CA` is throwing on IE11. Other `en-*` work as expected.

## Details

How to reproduce:

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <script src="https://polyfill.io/v3/polyfill.js?version=3.100.0&flags=gated&features=Intl.~locale.en-CA"></script>
</head>
<body>
  test
</body>
</html>
```

Again, when changing to `Intl.~locale.en-US` or `Intl.~locale.en-GB` it works as expected and no error is thrown.

## Additional information

This is how the error looks (I couldn't make any sense of it):
![image](https://user-images.githubusercontent.com/408962/103412975-03fcf400-4b78-11eb-942e-43ff861cabb1.png)

**Comment by romainmenke** [comment]
Error message : `RangeError: Invalid range pattern token`

`skeletonTokenToTable2` is called with `d-alt-variant` as argument.

@longlho

**Comment by longlho** [comment]
can u make a GH issue in the formatjs repo?

**Comment by romainmenke** [comment]
@aronwoost can you open an issue [here](https://github.com/formatjs/formatjs/issues?q=is%3Aopen+is%3Aissue) referencing this issue. Thank you!

**Comment by longlho** [comment]
should be fixed in latest version

**Comment by aronwoost** [comment]
Wow, thats super awesome! Thanks for the fix.

What can I do to update `polyfill-service`?

**Comment by JakeChampion** [comment]
> Wow, thats super awesome! Thanks for the fix.
> 
> What can I do to update `polyfill-service`?

I made a pull-request to update polyfill-service with the latest version of polyfill-library -- https://github.com/Financial-Times/polyfill-service/pull/2488

When that is merged it will be deployed to production

**Comment by aronwoost** [comment]
Thank you! ❤️
